include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("H_diag_1_j.F90", "w") do io
s = let
    func = FortranFunction(("h_i", ["o"]))
    F_oo = ("wf%fock_ij", false)
    ct2 = ("ct2", true)
    ct2_st2 = ("ct2_st2", true)
    FAA = ("FAA", true)
    ct1_st1 = ("ct1_st1", true)
    tAI = ("tAI", true)
    ct1_st3 = ("ct1_st3", true)
    tAIAI = ("tAIAI", true)
    ct3_st1 = ("ct3_st1", true)
    FII = ("FII", true)
    update_code!(func, ein"jj,->j", -1//2, [F_oo, ct2])
    update_code!(func, ein"jj,->j", 1//1, [F_oo, ct2_st2])
    update_code!(func, ein",->j", 1//2, [FAA, ct2])
    update_code!(func, ein",->j", -1//1, [FAA, ct2_st2])
    update_code!(func, ein"jj,,->j", -1//2, [F_oo, ct1_st1, tAI])
    update_code!(func, ein"jj,,->j", 1//1, [F_oo, ct1_st3, tAI])
    update_code!(func, ein"jj,,->j", -1//1, [F_oo, ct2_st2, tAIAI])
    update_code!(func, ein"jj,,->j", -1//1, [F_oo, ct3_st1, tAI])
    update_code!(func, ein",,->j", 1//2, [FAA, ct1_st1, tAI])
    update_code!(func, ein",,->j", -1//1, [FAA, ct1_st3, tAI])
    update_code!(func, ein",,->j", 3//1, [FAA, ct2_st2, tAIAI])
    update_code!(func, ein",,->j", 1//1, [FAA, ct3_st1, tAI])
    update_code!(func, ein",,->j", -2//1, [FII, ct2_st2, tAIAI])
    update_code!(func, ein"jj,,,->j", -1//1, [F_oo, ct2_st2, tAI, tAI])
    update_code!(func, ein",,,->j", 1//1, [FAA, ct2_st2, tAI, tAI])
    update_code!(func, ein"ii,->j", 1//1, [F_oo, ct2])
    update_code!(func, ein"kk,->j", -2//1, [F_oo, ct2_st2])
    update_code!(func, ein"kk,,->j", 1//1, [F_oo, ct1_st1, tAI])
    update_code!(func, ein"kk,,->j", -2//1, [F_oo, ct1_st3, tAI])
    update_code!(func, ein"kk,,->j", 2//1, [F_oo, ct2_st2, tAIAI])
    update_code!(func, ein"kk,,->j", 2//1, [F_oo, ct3_st1, tAI])
    update_code!(func, ein"kk,,,->j", 2//1, [F_oo, ct2_st2, tAI, tAI])
    finalize_eT_function(func, "H_diag_1_j", "doublet_ccsd")
end

println(io, s)
end
