include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("H_diag_1.F90", "w") do io
s = let
    func = FortranFunction(("h_ai", ["v", "o"]))
    F_oo = ("wf%fock_ij", false)
    st2 = ("st2", true)
    F_vv = ("wf%fock_ab", false)
    st4 = ("st4", true)
    ct1_st1 = ("ct1_st1", true)
    tAI = ("tAI", true)
    ct1_st3 = ("ct1_st3", true)
    ct2_st2 = ("ct2_st2", true)
    tAIAI = ("tAIAI", true)
    FAA = ("FAA", true)
    FII = ("FII", true)
    update_code!(func, ein"jj,->bj", -1//1, [F_oo, st2])
    update_code!(func, ein"bb,->bj", 1//1, [F_vv, st2])
    update_code!(func, ein"jj,->bj", 1//1, [F_oo, st4])
    update_code!(func, ein"bb,->bj", -1//1, [F_vv, st4])
    update_code!(func, ein"jj,,->bj", 1//1, [F_oo, ct1_st1, tAI])
    update_code!(func, ein"bb,,->bj", -1//1, [F_vv, ct1_st1, tAI])
    update_code!(func, ein"jj,,->bj", -2//1, [F_oo, ct1_st3, tAI])
    update_code!(func, ein"bb,,->bj", 2//1, [F_vv, ct1_st3, tAI])
    update_code!(func, ein"jj,,->bj", 1//1, [F_oo, ct2_st2, tAIAI])
    update_code!(func, ein"bb,,->bj", -1//1, [F_vv, ct2_st2, tAIAI])
    update_code!(func, ein",,->bj", -2//1, [FAA, ct2_st2, tAIAI])
    update_code!(func, ein",,->bj", 2//1, [FII, ct2_st2, tAIAI])
    update_code!(func, ein"jj,,,->bj", 1//1, [F_oo, ct2_st2, tAI, tAI])
    update_code!(func, ein"bb,,,->bj", -1//1, [F_vv, ct2_st2, tAI, tAI])
    update_code!(func, ein"kk,->bj", 2//1, [F_oo, st2])
    update_code!(func, ein"kk,->bj", -2//1, [F_oo, st4])
    update_code!(func, ein"kk,,->bj", -2//1, [F_oo, ct1_st1, tAI])
    update_code!(func, ein"kk,,->bj", 4//1, [F_oo, ct1_st3, tAI])
    update_code!(func, ein"kk,,->bj", -2//1, [F_oo, ct2_st2, tAIAI])
    update_code!(func, ein"kk,,,->bj", -2//1, [F_oo, ct2_st2, tAI, tAI])
    finalize_eT_function(func, "H_diag_1", "doublet_ccsd")
end

println(io, s)
end
