include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("H_diag_1_b.F90", "w") do io
s = let
    func = FortranFunction(("h_a", ["v"]))
    F_vv = ("wf%fock_ab", false)
    st2 = ("st2", true)
    st4 = ("st4", true)
    FII = ("FII", true)
    ct1_st1 = ("ct1_st1", true)
    tAI = ("tAI", true)
    ct1_st3 = ("ct1_st3", true)
    ct2_st2 = ("ct2_st2", true)
    tAIAI = ("tAIAI", true)
    FAA = ("FAA", true)
    F_oo = ("wf%fock_ij", false)
    update_code!(func, ein"bb,->b", -1//2, [F_vv, st2])
    update_code!(func, ein"bb,->b", 1//1, [F_vv, st4])
    update_code!(func, ein",->b", 1//2, [FII, st2])
    update_code!(func, ein",->b", -1//1, [FII, st4])
    update_code!(func, ein"bb,,->b", 1//2, [F_vv, ct1_st1, tAI])
    update_code!(func, ein"bb,,->b", -2//1, [F_vv, ct1_st3, tAI])
    update_code!(func, ein"bb,,->b", 1//1, [F_vv, ct2_st2, tAIAI])
    update_code!(func, ein",,->b", 2//1, [FAA, ct2_st2, tAIAI])
    update_code!(func, ein",,->b", -1//2, [FII, ct1_st1, tAI])
    update_code!(func, ein",,->b", 2//1, [FII, ct1_st3, tAI])
    update_code!(func, ein",,->b", -3//1, [FII, ct2_st2, tAIAI])
    update_code!(func, ein"bb,,,->b", 1//1, [F_vv, ct2_st2, tAI, tAI])
    update_code!(func, ein",,,->b", -1//1, [FII, ct2_st2, tAI, tAI])
    update_code!(func, ein"kk,->b", -1//1, [F_oo, st2])
    update_code!(func, ein"kk,->b", 2//1, [F_oo, st4])
    update_code!(func, ein"kk,,->b", 1//1, [F_oo, ct1_st1, tAI])
    update_code!(func, ein"kk,,->b", -4//1, [F_oo, ct1_st3, tAI])
    update_code!(func, ein"kk,,->b", 2//1, [F_oo, ct2_st2, tAIAI])
    update_code!(func, ein"kk,,,->b", 2//1, [F_oo, ct2_st2, tAI, tAI])
    finalize_eT_function(func, "H_diag_1_b", "doublet_ccsd")
end

println(io, s)
end
