include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_2_H_nu_1.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    F_vo = ("wf%fock_ai", false)
    r_vo = ("r_vo", true)
    L_oovo = ("L_oovo", true)
    L_vvvo = ("L_vvvo", true)
    L_vovv = ("L_vovv", true)
    F_ov = ("wf%fock_ia", false)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    L_ovvv = ("L_ovvv", true)
    L_ovoo = ("L_ovoo", true)
    g_ovvv = ("g_ovvv", true)
    g_ovoo = ("g_ovoo", true)
    update_code!(func, ein"bj,ck->bjck", 4//1, [F_vo, r_vo])
    update_code!(func, ein"bk,cj->bjck", -2//1, [F_vo, r_vo])
    update_code!(func, ein"cj,bk->bjck", -2//1, [F_vo, r_vo])
    update_code!(func, ein"ck,bj->bjck", 4//1, [F_vo, r_vo])
    update_code!(func, ein"ijck,bi->bjck", -2//1, [L_oovo, r_vo])
    update_code!(func, ein"ikbj,ci->bjck", -2//1, [L_oovo, r_vo])
    update_code!(func, ein"back,aj->bjck", 2//1, [L_vvvo, r_vo])
    update_code!(func, ein"bjca,ak->bjck", 2//1, [L_vovv, r_vo])
    update_code!(func, ein"ia,aj,bick->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,ak,bjci->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bi,ajck->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bj,aick->bjck", 4//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bk,aicj->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,ci,akbj->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,cj,aibk->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,ck,aibj->bjck", 4//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"iabd,ai,ckdj->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,dj,aick->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,ai,bjdk->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,dk,aibj->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"ialj,ai,blck->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,bl,aick->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,ai,bjcl->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,cl,aibj->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"iabd,ak,cidj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,ci,akdj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,cj,aidk->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,ck,aidj->bjck", 4//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,dk,aicj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,aj,bidk->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,bi,ajdk->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,bj,aidk->bjck", 4//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,bk,aidj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iacd,dj,aibk->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"ialj,ak,blci->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,bk,aicl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,ci,akbl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,ck,aibl->bjck", -4//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,cl,aibk->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,aj,bicl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,bi,ajcl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,bj,aicl->bjck", -4//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,bl,aicj->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialk,cj,aibl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    finalize_eT_function(func, "mu_2_H_nu_1", "doublet_ccsd")
end

println(io, s)
end
