include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_2_H_nu_1_s.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    F_vo = ("wf%fock_ai", false)
    r_vo = ("r_vo", true)
    g_oovo = ("g_oovo", true)
    g_vvvo = ("g_vvvo", true)
    F_ov = ("wf%fock_ia", false)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    L_ovvv = ("L_ovvv", true)
    L_ovoo = ("L_ovoo", true)
    g_ovvv = ("g_ovvv", true)
    g_ovoo = ("g_ovoo", true)
    update_code!(func, ein"bj,ck->bjck", 4//1, [F_vo, r_vo])
    update_code!(func, ein"bk,cj->bjck", -2//1, [F_vo, r_vo])
    update_code!(func, ein"ijbk,ci->bjck", 2//1, [g_oovo, r_vo])
    update_code!(func, ein"ijck,bi->bjck", -4//1, [g_oovo, r_vo])
    update_code!(func, ein"bacj,ak->bjck", -2//1, [g_vvvo, r_vo])
    update_code!(func, ein"back,aj->bjck", 4//1, [g_vvvo, r_vo])
    update_code!(func, ein"ia,aj,bick->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bi,ajck->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bj,aick->bjck", 4//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"ia,bk,aicj->bjck", -2//1, [F_ov, r_vo, u_vovo])
    update_code!(func, ein"iabd,ai,ckdj->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,dj,aick->bjck", 2//1, [L_ovvv, r_vo, u_vovo])
    update_code!(func, ein"ialj,ai,blck->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,bl,aick->bjck", -2//1, [L_ovoo, r_vo, u_vovo])
    update_code!(func, ein"iabd,ak,cidj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,ci,akdj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,cj,aidk->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,ck,aidj->bjck", 4//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"iabd,dk,aicj->bjck", -2//1, [g_ovvv, r_vo, u_vovo])
    update_code!(func, ein"ialj,ak,blci->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,bk,aicl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,ci,akbl->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,ck,aibl->bjck", -4//1, [g_ovoo, r_vo, u_vovo])
    update_code!(func, ein"ialj,cl,aibk->bjck", 2//1, [g_ovoo, r_vo, u_vovo])
    finalize_eT_function(func, "mu_2_H_nu_1_s", "doublet_ccsd")
end

println(io, s)
end
