include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_3_H_nu_1_s.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    LAIxx_vo = ("LAIxx_vo", true)
    r_vo = ("r_vo", true)
    gAIxx_vo = ("gAIxx_vo", true)
    gAxxI_ov = ("gAxxI_ov", true)
    gAxxx_ovo = ("gAxxx_ovo", true)
    rxI_v = ("rxI_v", true)
    gxIxx_vvo = ("gxIxx_vvo", true)
    rAx_o = ("rAx_o", true)
    F_vv = ("wf%fock_ab", false)
    uAIxx_vo = ("uAIxx_vo", true)
    F_oo = ("wf%fock_ij", false)
    rAI = ("rAI", true)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    uxIxx_vvo = ("uxIxx_vvo", true)
    uxxxI_vov = ("uxxxI_vov", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    FAx_v = ("FAx_v", true)
    FxI_o = ("FxI_o", true)
    L_voov = ("L_voov", true)
    L_vvoo = ("L_vvoo", true)
    L_oooo = ("L_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAIxx_ov = ("LAIxx_ov", true)
    LAxxx_vvv = ("LAxxx_vvv", true)
    LAxxx_voo = ("LAxxx_voo", true)
    LAxxx_oov = ("LAxxx_oov", true)
    LxIxx_ooo = ("LxIxx_ooo", true)
    LxIxx_vov = ("LxIxx_vov", true)
    LxxxI_vvo = ("LxxxI_vvo", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_voov = ("g_voov", true)
    g_vvoo = ("g_vvoo", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAxxx_oov = ("gAxxx_oov", true)
    gAxxx_vvv = ("gAxxx_vvv", true)
    gAxxx_voo = ("gAxxx_voo", true)
    gxIxx_vov = ("gxIxx_vov", true)
    gxIxx_ooo = ("gxIxx_ooo", true)
    gxxxI_vvo = ("gxxxI_vvo", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    tAxxx_ovo = ("tAxxx_ovo", true)
    t_vovo = ("t_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    txIxx_vvo = ("txIxx_vvo", true)
    txxxI_vov = ("txxxI_vov", true)
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"bj,ck->bjck", 2//1, [LAIxx_vo, r_vo])
    update_code!(func, ein"bk,cj->bjck", -2//1, [gAIxx_vo, r_vo])
    update_code!(func, ein"jc,bk->bjck", 1//1, [gAxxI_ov, r_vo])
    update_code!(func, ein"jbk,c->bjck", 1//1, [gAxxx_ovo, rxI_v])
    update_code!(func, ein"jck,b->bjck", -2//1, [gAxxx_ovo, rxI_v])
    update_code!(func, ein"bcj,k->bjck", 1//1, [gxIxx_vvo, rAx_o])
    update_code!(func, ein"bck,j->bjck", -2//1, [gxIxx_vvo, rAx_o])
    update_code!(func, ein"bd,cj,dk->bjck", -1//1, [F_vv, r_vo, uAIxx_vo])
    update_code!(func, ein"bd,ck,dj->bjck", 2//1, [F_vv, r_vo, uAIxx_vo])
    update_code!(func, ein"lj,bk,cl->bjck", 1//1, [F_oo, r_vo, uAIxx_vo])
    update_code!(func, ein"lj,ck,bl->bjck", -2//1, [F_oo, r_vo, uAIxx_vo])
    update_code!(func, ein"bd,,ckdj->bjck", 2//1, [F_vv, rAI, u_vovo])
    update_code!(func, ein"lj,,blck->bjck", -2//1, [F_oo, rAI, u_vovo])
    update_code!(func, ein"bd,k,cdj->bjck", -1//1, [F_vv, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bd,j,ckd->bjck", -1//1, [F_vv, rAx_o, uxxxI_vov])
    update_code!(func, ein"lj,k,blc->bjck", 1//1, [F_oo, rAx_o, uxxxI_vov])
    update_code!(func, ein"bd,c,kdj->bjck", -1//1, [F_vv, rxI_v, uAxxx_ovo])
    update_code!(func, ein"lj,b,lck->bjck", 1//1, [F_oo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"lj,c,kbl->bjck", 1//1, [F_oo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"d,bj,ckd->bjck", 2//1, [FAx_v, r_vo, uxxxI_vov])
    update_code!(func, ein"d,bk,cjd->bjck", -1//1, [FAx_v, r_vo, uxxxI_vov])
    update_code!(func, ein"d,b,ckdj->bjck", -1//1, [FAx_v, rxI_v, u_vovo])
    update_code!(func, ein"l,bj,lck->bjck", -2//1, [FxI_o, r_vo, uAxxx_ovo])
    update_code!(func, ein"l,bk,lcj->bjck", 1//1, [FxI_o, r_vo, uAxxx_ovo])
    update_code!(func, ein"l,j,blck->bjck", 1//1, [FxI_o, rAx_o, u_vovo])
    update_code!(func, ein"bjld,ck,dl->bjck", 2//1, [L_voov, r_vo, uAIxx_vo])
    update_code!(func, ein"bjld,cl,dk->bjck", -1//1, [L_voov, r_vo, uAIxx_vo])
    update_code!(func, ein"bjld,dk,cl->bjck", -1//1, [L_voov, r_vo, uAIxx_vo])
    update_code!(func, ein"bkld,cj,dl->bjck", -1//1, [L_voov, r_vo, uAIxx_vo])
    update_code!(func, ein"bdlk,cl,dj->bjck", -1//1, [L_vvoo, r_vo, uAIxx_vo])
    update_code!(func, ein"bdlk,dj,cl->bjck", -1//1, [L_vvoo, r_vo, uAIxx_vo])
    update_code!(func, ein"ljmk,bl,cm->bjck", 1//1, [L_oooo, r_vo, uAIxx_vo])
    update_code!(func, ein"bjld,,ckdl->bjck", 2//1, [L_voov, rAI, u_vovo])
    update_code!(func, ein"bjld,k,cdl->bjck", -1//1, [L_voov, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bjld,l,ckd->bjck", -1//1, [L_voov, rAx_o, uxxxI_vov])
    update_code!(func, ein"bjld,c,kdl->bjck", -1//1, [L_voov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"bjld,d,lck->bjck", -1//1, [L_voov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"ld,bj,ckdl->bjck", 2//1, [LAIxx_ov, r_vo, u_vovo])
    update_code!(func, ein"ld,bk,cjdl->bjck", -1//1, [LAIxx_ov, r_vo, u_vovo])
    update_code!(func, ein"ld,bl,ckdj->bjck", -1//1, [LAIxx_ov, r_vo, u_vovo])
    update_code!(func, ein"ld,dj,blck->bjck", -1//1, [LAIxx_ov, r_vo, u_vovo])
    update_code!(func, ein"dbe,ej,ckd->bjck", 1//1, [LAxxx_vvv, r_vo, uxxxI_vov])
    update_code!(func, ein"dlj,bl,ckd->bjck", -1//1, [LAxxx_voo, r_vo, uxxxI_vov])
    update_code!(func, ein"jld,b,ckdl->bjck", -1//1, [LAxxx_oov, rxI_v, u_vovo])
    update_code!(func, ein"dbe,d,ckej->bjck", 1//1, [LAxxx_vvv, rxI_v, u_vovo])
    update_code!(func, ein"dlj,d,blck->bjck", -1//1, [LAxxx_voo, rxI_v, u_vovo])
    update_code!(func, ein"lmj,bm,lck->bjck", 1//1, [LxIxx_ooo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bld,j,ckdl->bjck", -1//1, [LxIxx_vov, rAx_o, u_vovo])
    update_code!(func, ein"lmj,l,bmck->bjck", 1//1, [LxIxx_ooo, rAx_o, u_vovo])
    update_code!(func, ein"bdl,dj,lck->bjck", -1//1, [LxxxI_vvo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,l,ckdj->bjck", -1//1, [LxxxI_vvo, rAx_o, u_vovo])
    update_code!(func, ein"bdce,dj,ek->bjck", 2//1, [g_vvvv, r_vo, uAIxx_vo])
    update_code!(func, ein"bdce,dk,ej->bjck", -1//1, [g_vvvv, r_vo, uAIxx_vo])
    update_code!(func, ein"bkld,,cjdl->bjck", -2//1, [g_voov, rAI, u_vovo])
    update_code!(func, ein"bdlk,,cldj->bjck", -2//1, [g_vvoo, rAI, u_vovo])
    update_code!(func, ein"bkld,j,cdl->bjck", 1//1, [g_voov, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bdce,j,dek->bjck", -1//1, [g_vvvv, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bdlk,l,cdj->bjck", 1//1, [g_vvoo, rAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmk,l,bcm->bjck", -1//1, [g_oooo, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bkld,l,cjd->bjck", 1//1, [g_voov, rAx_o, uxxxI_vov])
    update_code!(func, ein"bdlk,j,cld->bjck", 1//1, [g_vvoo, rAx_o, uxxxI_vov])
    update_code!(func, ein"bkld,c,jdl->bjck", 1//1, [g_voov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"bkld,d,lcj->bjck", 1//1, [g_voov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"bdce,d,jek->bjck", -1//1, [g_vvvv, rxI_v, uAxxx_ovo])
    update_code!(func, ein"bdlk,c,ldj->bjck", 1//1, [g_vvoo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"bdlk,d,jcl->bjck", 1//1, [g_vvoo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmk,b,lcm->bjck", -1//1, [g_oooo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"jld,bk,cdl->bjck", 1//1, [gAxxx_oov, r_vo, uxIxx_vvo])
    update_code!(func, ein"jld,ck,bdl->bjck", -2//1, [gAxxx_oov, r_vo, uxIxx_vvo])
    update_code!(func, ein"jld,cl,bdk->bjck", 1//1, [gAxxx_oov, r_vo, uxIxx_vvo])
    update_code!(func, ein"jld,dk,bcl->bjck", 1//1, [gAxxx_oov, r_vo, uxIxx_vvo])
    update_code!(func, ein"dbe,cj,dek->bjck", -1//1, [gAxxx_vvv, r_vo, uxIxx_vvo])
    update_code!(func, ein"dbe,ck,dej->bjck", 2//1, [gAxxx_vvv, r_vo, uxIxx_vvo])
    update_code!(func, ein"dbe,dk,cej->bjck", -1//1, [gAxxx_vvv, r_vo, uxIxx_vvo])
    update_code!(func, ein"dbe,ek,cjd->bjck", -1//1, [gAxxx_vvv, r_vo, uxxxI_vov])
    update_code!(func, ein"dlj,bk,cld->bjck", 1//1, [gAxxx_voo, r_vo, uxxxI_vov])
    update_code!(func, ein"dlj,ck,bld->bjck", -2//1, [gAxxx_voo, r_vo, uxxxI_vov])
    update_code!(func, ein"dlj,cl,bkd->bjck", 1//1, [gAxxx_voo, r_vo, uxxxI_vov])
    update_code!(func, ein"dlj,dk,blc->bjck", 1//1, [gAxxx_voo, r_vo, uxxxI_vov])
    update_code!(func, ein"jld,c,bkdl->bjck", 1//1, [gAxxx_oov, rxI_v, u_vovo])
    update_code!(func, ein"dbe,c,dkej->bjck", -1//1, [gAxxx_vvv, rxI_v, u_vovo])
    update_code!(func, ein"dlj,c,bldk->bjck", 1//1, [gAxxx_voo, rxI_v, u_vovo])
    update_code!(func, ein"bld,cj,kdl->bjck", 1//1, [gxIxx_vov, r_vo, uAxxx_ovo])
    update_code!(func, ein"bld,ck,jdl->bjck", -2//1, [gxIxx_vov, r_vo, uAxxx_ovo])
    update_code!(func, ein"bld,cl,jdk->bjck", 1//1, [gxIxx_vov, r_vo, uAxxx_ovo])
    update_code!(func, ein"bld,dk,jcl->bjck", 1//1, [gxIxx_vov, r_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,bk,lcm->bjck", -1//1, [gxIxx_ooo, r_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,ck,lbm->bjck", 2//1, [gxIxx_ooo, r_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,cl,kbm->bjck", -1//1, [gxIxx_ooo, r_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,cm,lbk->bjck", -1//1, [gxIxx_ooo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bld,k,cjdl->bjck", 1//1, [gxIxx_vov, rAx_o, u_vovo])
    update_code!(func, ein"lmj,k,bmcl->bjck", -1//1, [gxIxx_ooo, rAx_o, u_vovo])
    update_code!(func, ein"bdl,cj,ldk->bjck", 1//1, [gxxxI_vvo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,ck,ldj->bjck", -2//1, [gxxxI_vvo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,cl,kdj->bjck", 1//1, [gxxxI_vvo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,dk,lcj->bjck", 1//1, [gxxxI_vvo, r_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,k,cldj->bjck", 1//1, [gxxxI_vvo, rAx_o, u_vovo])
    update_code!(func, ein"ldme,dl,jcm,bek->bjck", 1//1, [L_ovov, r_vo, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,dl,jek,bcm->bjck", 1//1, [L_ovov, r_vo, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,dl,mbk,cje->bjck", 1//1, [L_ovov, r_vo, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bj,ckem,dl->bjck", 2//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bk,cjem,dl->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bl,ckdj,em->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bl,ckem,dj->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,blck,em->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,ckem,bl->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dl,bmck,ej->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dl,ckej,bm->bjck", -1//1, [L_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dl,mbj,cke->bjck", -1//1, [L_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,,bjdl,cmek->bjck", -4//1, [L_ovov, rAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,,bkdl,cmej->bjck", 2//1, [L_ovov, rAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,l,bem,ckdj->bjck", 1//1, [L_ovov, rAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,l,cmd,bjek->bjck", 1//1, [L_ovov, rAx_o, txxxI_vov, u_vovo])
    update_code!(func, ein"ldme,j,ckem,bdl->bjck", -1//1, [L_ovov, rAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,d,lbk,cjem->bjck", 1//1, [L_ovov, rxI_v, tAxxx_ovo, u_vovo])
    update_code!(func, ein"ldme,b,ckem,jdl->bjck", -1//1, [L_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,ckem,lbj->bjck", -1//1, [L_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,bj,cdm,kel->bjck", 2//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bj,dek,lcm->bjck", 2//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bk,cdm,jel->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bk,dej,lcm->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cdm,kej->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cej,kdm->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,dek,jcm->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bcm,lek->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bek,lcm->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,cel,kbm->bjck", -1//1, [g_ovov, r_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bj,cle,mdk->bjck", 2//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bk,cle,mdj->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cje,mdk->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cmd,jek->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,dke,mcj->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bke,mcl->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bmc,kel->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,cle,mbk->bjck", -1//1, [g_ovov, r_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bj,clem,dk->bjck", -2//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bj,dkem,cl->bjck", -2//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bk,clem,dj->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bk,djem,cl->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bl,cjem,dk->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bl,cmdj,ek->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bl,djek,cm->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,bkem,cl->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,blcm,ek->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,blek,cm->bjck", 1//1, [g_ovov, r_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,bj,kdl,cem->bjck", -2//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bj,lck,dem->bjck", -2//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bk,jdl,cem->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bk,lcj,dem->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bl,kdj,cem->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bl,kem,cdj->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,dj,kbl,cem->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,dj,lck,bem->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bj,lem,ckd->bjck", -2//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bk,lem,cjd->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bl,jem,ckd->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bl,mck,dje->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bl,mdj,cke->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,dj,kem,blc->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,dj,mbl,cke->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,dj,mck,ble->bjck", 1//1, [g_ovov, r_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,,bjcl,dkem->bjck", -4//1, [g_ovov, rAI, t_vovo, u_vovo])
    update_code!(func, ein"ldme,,bkcl,djem->bjck", 2//1, [g_ovov, rAI, t_vovo, u_vovo])
    update_code!(func, ein"ldme,,bjdk,clem->bjck", -2//1, [g_ovov, rAI, u_vovo, u_vovo])
    update_code!(func, ein"ldme,l,cjdm,bek->bjck", 1//1, [g_ovov, rAx_o, t_vovo, txIxx_vvo])
    update_code!(func, ein"ldme,l,bjdm,cke->bjck", 4//1, [g_ovov, rAx_o, t_vovo, txxxI_vov])
    update_code!(func, ein"ldme,l,bkdm,cje->bjck", -2//1, [g_ovov, rAx_o, t_vovo, txxxI_vov])
    update_code!(func, ein"ldme,l,cmdk,bje->bjck", -2//1, [g_ovov, rAx_o, t_vovo, txxxI_vov])
    update_code!(func, ein"ldme,l,bjcm,dek->bjck", 2//1, [g_ovov, rAx_o, t_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,l,bkcm,dej->bjck", -1//1, [g_ovov, rAx_o, t_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,l,cmdj,bek->bjck", -1//1, [g_ovov, rAx_o, t_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,j,cdm,bkel->bjck", -1//1, [g_ovov, rAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,j,dek,blcm->bjck", -1//1, [g_ovov, rAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,l,bcm,djek->bjck", -1//1, [g_ovov, rAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,l,bej,ckdm->bjck", -1//1, [g_ovov, rAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,j,cle,bmdk->bjck", -1//1, [g_ovov, rAx_o, txxxI_vov, u_vovo])
    update_code!(func, ein"ldme,j,bkdl,cem->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,j,blck,dem->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,j,clem,bdk->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,j,dkem,bcl->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,j,blem,ckd->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,l,cjem,bkd->bjck", 1//1, [g_ovov, rAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,l,ckem,bjd->bjck", -2//1, [g_ovov, rAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,b,cjdm,kel->bjck", -1//1, [g_ovov, rxI_v, t_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,clej,mdk->bjck", -1//1, [g_ovov, rxI_v, t_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,djek,lcm->bjck", -1//1, [g_ovov, rxI_v, t_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,jcl,bkem->bjck", -1//1, [g_ovov, rxI_v, tAxxx_ovo, u_vovo])
    update_code!(func, ein"ldme,d,jcm,blek->bjck", -1//1, [g_ovov, rxI_v, tAxxx_ovo, u_vovo])
    update_code!(func, ein"ldme,d,jek,blcm->bjck", -1//1, [g_ovov, rxI_v, tAxxx_ovo, u_vovo])
    update_code!(func, ein"ldme,b,cjem,kdl->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,ckdj,lem->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,clem,jdk->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,djem,lck->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,b,dkem,jcl->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,blck,jem->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,bmck,lej->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,ckej,lbm->bjck", 1//1, [g_ovov, rxI_v, u_vovo, uAxxx_ovo])
    finalize_eT_function(func, "mu_4_H_nu_1_s", "doublet_ccsd")
end

println(io, s)
end
