include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_3_H_nu_2_s.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    F_vo = ("wf%fock_ai", false)
    rAIxx_vo = ("rAIxx_vo", true)
    rAxxI_ov = ("rAxxI_ov", true)
    FAx_o = ("FAx_o", true)
    rxIxx_vvo = ("rxIxx_vvo", true)
    rxxxI_vov = ("rxxxI_vov", true)
    FxI_v = ("FxI_v", true)
    rAxxx_ovo = ("rAxxx_ovo", true)
    L_vooo = ("L_vooo", true)
    LAIxx_vv = ("LAIxx_vv", true)
    r_vovo = ("r_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAIxx_oo = ("LAIxx_oo", true)
    LAxxx_vvo = ("LAxxx_vvo", true)
    LxIxx_voo = ("LxIxx_voo", true)
    LxxxI_voo = ("LxxxI_voo", true)
    g_vovv = ("g_vovv", true)
    gAxxx_ovv = ("gAxxx_ovv", true)
    gAxxx_ooo = ("gAxxx_ooo", true)
    gAxxx_vvo = ("gAxxx_vvo", true)
    gxIxx_vvv = ("gxIxx_vvv", true)
    F_ov = ("wf%fock_ia", false)
    uAIxx_vo = ("uAIxx_vo", true)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    uxIxx_vvo = ("uxIxx_vvo", true)
    uxxxI_vov = ("uxxxI_vov", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    L_vvov = ("L_vvov", true)
    L_ooov = ("L_ooov", true)
    LAxxx_vov = ("LAxxx_vov", true)
    LxIxx_oov = ("LxIxx_oov", true)
    g_vvov = ("g_vvov", true)
    g_ooov = ("g_ooov", true)
    gAxxx_vov = ("gAxxx_vov", true)
    gxIxx_oov = ("gxIxx_oov", true)
    update_code!(func, ein"bj,ck->bjck", 4//1, [F_vo, rAIxx_vo])
    update_code!(func, ein"bk,cj->bjck", -2//1, [F_vo, rAIxx_vo])
    update_code!(func, ein"bj,kc->bjck", -2//1, [F_vo, rAxxI_ov])
    update_code!(func, ein"bk,jc->bjck", 1//1, [F_vo, rAxxI_ov])
    update_code!(func, ein"j,bck->bjck", -2//1, [FAx_o, rxIxx_vvo])
    update_code!(func, ein"j,bkc->bjck", 1//1, [FAx_o, rxxxI_vov])
    update_code!(func, ein"b,jck->bjck", -2//1, [FxI_v, rAxxx_ovo])
    update_code!(func, ein"b,kcj->bjck", 1//1, [FxI_v, rAxxx_ovo])
    update_code!(func, ein"bjlk,cl->bjck", -2//1, [L_vooo, rAIxx_vo])
    update_code!(func, ein"bjlk,lc->bjck", 1//1, [L_vooo, rAxxI_ov])
    update_code!(func, ein"bd,cjdk->bjck", -1//1, [LAIxx_vv, r_vovo])
    update_code!(func, ein"bd,ckdj->bjck", 2//1, [LAIxx_vv, r_vovo])
    update_code!(func, ein"lj,bkcl->bjck", 1//1, [LAIxx_oo, r_vovo])
    update_code!(func, ein"lj,blck->bjck", -2//1, [LAIxx_oo, r_vovo])
    update_code!(func, ein"dbj,cdk->bjck", -1//1, [LAxxx_vvo, rxIxx_vvo])
    update_code!(func, ein"dbj,ckd->bjck", 2//1, [LAxxx_vvo, rxxxI_vov])
    update_code!(func, ein"blk,jcl->bjck", 1//1, [LxIxx_voo, rAxxx_ovo])
    update_code!(func, ein"bjl,kcl->bjck", 1//1, [LxxxI_voo, rAxxx_ovo])
    update_code!(func, ein"bjl,lck->bjck", -2//1, [LxxxI_voo, rAxxx_ovo])
    update_code!(func, ein"bkl,lcj->bjck", 1//1, [LxxxI_voo, rAxxx_ovo])
    update_code!(func, ein"bjcd,dk->bjck", 4//1, [g_vovv, rAIxx_vo])
    update_code!(func, ein"bkcd,dj->bjck", -2//1, [g_vovv, rAIxx_vo])
    update_code!(func, ein"bjcd,kd->bjck", -2//1, [g_vovv, rAxxI_ov])
    update_code!(func, ein"bkcd,jd->bjck", 1//1, [g_vovv, rAxxI_ov])
    update_code!(func, ein"jcd,bdk->bjck", -2//1, [gAxxx_ovv, rxIxx_vvo])
    update_code!(func, ein"jlk,bcl->bjck", 2//1, [gAxxx_ooo, rxIxx_vvo])
    update_code!(func, ein"dbk,cdj->bjck", 1//1, [gAxxx_vvo, rxIxx_vvo])
    update_code!(func, ein"jcd,bkd->bjck", 1//1, [gAxxx_ovv, rxxxI_vov])
    update_code!(func, ein"jlk,blc->bjck", -1//1, [gAxxx_ooo, rxxxI_vov])
    update_code!(func, ein"dbk,cjd->bjck", -2//1, [gAxxx_vvo, rxxxI_vov])
    update_code!(func, ein"bcd,jdk->bjck", -2//1, [gxIxx_vvv, rAxxx_ovo])
    update_code!(func, ein"bcd,kdj->bjck", 1//1, [gxIxx_vvv, rAxxx_ovo])
    update_code!(func, ein"ld,bjcl,dk->bjck", -2//1, [F_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bjdk,cl->bjck", -2//1, [F_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bkcl,dj->bjck", 1//1, [F_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bkdj,cl->bjck", 1//1, [F_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bj,ckdl->bjck", 4//1, [F_ov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ld,bk,cjdl->bjck", -2//1, [F_ov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ld,bl,ckdj->bjck", -2//1, [F_ov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ld,dj,blck->bjck", -2//1, [F_ov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ld,jb,ckdl->bjck", -2//1, [F_ov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ld,jc,bkdl->bjck", 1//1, [F_ov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ld,jd,blck->bjck", 1//1, [F_ov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ld,lb,ckdj->bjck", 1//1, [F_ov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ld,jbk,cdl->bjck", 1//1, [F_ov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,jck,bdl->bjck", -2//1, [F_ov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,jcl,bdk->bjck", 1//1, [F_ov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,jdk,bcl->bjck", 1//1, [F_ov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,jbl,ckd->bjck", 1//1, [F_ov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ld,lbj,ckd->bjck", -2//1, [F_ov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ld,lbk,cjd->bjck", 1//1, [F_ov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ld,bcj,kdl->bjck", 1//1, [F_ov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bck,jdl->bjck", -2//1, [F_ov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bcl,jdk->bjck", 1//1, [F_ov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bdj,lck->bjck", 1//1, [F_ov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bdk,jcl->bjck", 1//1, [F_ov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bjd,lck->bjck", -2//1, [F_ov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ld,bkd,lcj->bjck", 1//1, [F_ov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,cjdk,el->bjck", -1//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,cjel,dk->bjck", -1//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,ckdj,el->bjck", 2//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,ckel,dj->bjck", 2//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,cldj,ek->bjck", -1//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,clek,dj->bjck", -1//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,djek,cl->bjck", -1//1, [L_vvov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,bkcl,dm->bjck", 1//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,bkdm,cl->bjck", 1//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,blck,dm->bjck", -2//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,blcm,dk->bjck", 1//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,bldk,cm->bjck", 1//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,ckdm,bl->bjck", -2//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,cmdk,bl->bjck", 1//1, [L_ooov, r_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,dj,ckel->bjck", 2//1, [L_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,el,ckdj->bjck", 2//1, [L_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,bl,ckdm->bjck", -2//1, [L_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,dm,blck->bjck", -2//1, [L_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,jd,ckel->bjck", -1//1, [L_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,le,ckdj->bjck", -1//1, [L_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,lb,ckdm->bjck", 1//1, [L_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,md,blck->bjck", 1//1, [L_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,kdj,cel->bjck", -1//1, [L_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,kel,cdj->bjck", -1//1, [L_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,kbl,cdm->bjck", 1//1, [L_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,jel,ckd->bjck", -1//1, [L_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,ldj,cke->bjck", -1//1, [L_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,kdm,blc->bjck", 1//1, [L_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,mbl,ckd->bjck", 1//1, [L_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,cdj,kel->bjck", -1//1, [L_vvov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,cel,kdj->bjck", -1//1, [L_vvov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,bdm,lck->bjck", 1//1, [L_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,cdm,kbl->bjck", 1//1, [L_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,dje,lck->bjck", -1//1, [L_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,blc,kdm->bjck", 1//1, [L_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,bld,mck->bjck", 1//1, [L_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dle,bjel,ckd->bjck", 2//1, [LAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,bkel,cjd->bjck", -1//1, [LAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,blej,ckd->bjck", -1//1, [LAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,bdj,ckel->bjck", -1//1, [LAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bel,ckdj->bjck", -1//1, [LAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,dej,blck->bjck", -1//1, [LAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bjd,ckel->bjck", 2//1, [LAxxx_vov, rxxxI_vov, u_vovo])
    update_code!(func, ein"dle,bkd,cjel->bjck", -1//1, [LAxxx_vov, rxxxI_vov, u_vovo])
    update_code!(func, ein"dle,bld,ckej->bjck", -1//1, [LAxxx_vov, rxxxI_vov, u_vovo])
    update_code!(func, ein"lmd,bjdm,lck->bjck", -2//1, [LxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bkdm,lcj->bjck", 1//1, [LxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bmdj,lck->bjck", 1//1, [LxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,jbl,ckdm->bjck", 1//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,jdm,blck->bjck", 1//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,lbj,ckdm->bjck", -2//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,lbk,cjdm->bjck", 1//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,lbm,ckdj->bjck", 1//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,ldj,bmck->bjck", 1//1, [LxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"bdle,cj,dkel->bjck", -2//1, [g_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,ck,djel->bjck", 4//1, [g_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,cl,djek->bjck", -2//1, [g_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,dk,cjel->bjck", -2//1, [g_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,ek,cldj->bjck", -2//1, [g_vvov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,bk,cldm->bjck", 2//1, [g_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,ck,bldm->bjck", -4//1, [g_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,cl,bkdm->bjck", 2//1, [g_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,cm,bldk->bjck", 2//1, [g_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"ljmd,dk,blcm->bjck", 2//1, [g_ooov, rAIxx_vo, u_vovo])
    update_code!(func, ein"bdle,jc,dkel->bjck", 1//1, [g_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,kc,djel->bjck", -2//1, [g_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,kd,cjel->bjck", 1//1, [g_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,ke,cldj->bjck", 1//1, [g_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,lc,djek->bjck", 1//1, [g_vvov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,kb,cldm->bjck", -1//1, [g_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,kc,bldm->bjck", 2//1, [g_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,kd,blcm->bjck", -1//1, [g_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,lc,bkdm->bjck", -1//1, [g_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"ljmd,mc,bldk->bjck", -1//1, [g_ooov, rAxxI_ov, u_vovo])
    update_code!(func, ein"bdle,jck,del->bjck", -2//1, [g_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,jcl,dek->bjck", 1//1, [g_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,jdk,cel->bjck", 1//1, [g_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,kcj,del->bjck", 1//1, [g_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,lek,cdj->bjck", 1//1, [g_vvov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,kcl,bdm->bjck", -1//1, [g_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,lbk,cdm->bjck", -1//1, [g_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,lck,bdm->bjck", 2//1, [g_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,lcm,bdk->bjck", -1//1, [g_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,ldk,bcm->bjck", -1//1, [g_ooov, rAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,jek,cld->bjck", 1//1, [g_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,kcl,dje->bjck", 1//1, [g_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,lcj,dke->bjck", 1//1, [g_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,lck,dje->bjck", -2//1, [g_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,ldk,cje->bjck", 1//1, [g_vvov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,kcm,bld->bjck", -1//1, [g_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,mbk,cld->bjck", -1//1, [g_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,mck,bld->bjck", 2//1, [g_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,mcl,bkd->bjck", -1//1, [g_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,mdk,blc->bjck", -1//1, [g_ooov, rAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,cdk,jel->bjck", 1//1, [g_vvov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,cek,ldj->bjck", 1//1, [g_vvov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,dek,jcl->bjck", 1//1, [g_vvov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,bck,ldm->bjck", 2//1, [g_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,bcl,kdm->bjck", -1//1, [g_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,bcm,ldk->bjck", -1//1, [g_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,bdk,lcm->bjck", -1//1, [g_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,cdk,mbl->bjck", -1//1, [g_ooov, rxIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,cjd,kel->bjck", 1//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,cje,ldk->bjck", 1//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,ckd,jel->bjck", -2//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,cke,ldj->bjck", -2//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,cld,jek->bjck", 1//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,cle,kdj->bjck", 1//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,dke,lcj->bjck", 1//1, [g_vvov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,bkc,ldm->bjck", -1//1, [g_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,bkd,mcl->bjck", -1//1, [g_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,ckd,mbl->bjck", 2//1, [g_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,cld,mbk->bjck", -1//1, [g_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,cmd,kbl->bjck", -1//1, [g_ooov, rxxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dle,bjcl,dek->bjck", -2//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,bjdk,cel->bjck", -2//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,bkcl,dej->bjck", 1//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,bkdj,cel->bjck", 1//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,bldk,cej->bjck", 1//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,djek,bcl->bjck", 1//1, [gAxxx_vov, r_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,bjek,cld->bjck", -2//1, [gAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,bkej,cld->bjck", 1//1, [gAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,blek,cjd->bjck", 1//1, [gAxxx_vov, r_vovo, uxxxI_vov])
    update_code!(func, ein"dle,bcj,dkel->bjck", 1//1, [gAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bck,djel->bjck", -2//1, [gAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bcl,djek->bjck", 1//1, [gAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bdk,cjel->bjck", 1//1, [gAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"dle,bek,cldj->bjck", 1//1, [gAxxx_vov, rxIxx_vvo, u_vovo])
    update_code!(func, ein"lmd,bjcl,kdm->bjck", 2//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bjcm,ldk->bjck", 2//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bjdk,lcm->bjck", 2//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bkcl,jdm->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bkcm,ldj->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bkdj,lcm->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,blcm,jdk->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bldk,jcm->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,bmdk,lcj->bjck", -1//1, [gxIxx_oov, r_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,jbk,cldm->bjck", -1//1, [gxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,jck,bldm->bjck", 2//1, [gxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,jcl,bkdm->bjck", -1//1, [gxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,jcm,bldk->bjck", -1//1, [gxIxx_oov, rAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,jdk,blcm->bjck", -1//1, [gxIxx_oov, rAxxx_ovo, u_vovo])
    finalize_eT_function(func, "mu_4_H_nu_2_s", "doublet_ccsd")
end

println(io, s)
end
