include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_4_H_nu_2_ss.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    L_vovo = ("L_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    rAIAI = ("rAIAI", true)
    gAIAI = ("gAIAI", true)
    r_vovo = ("r_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAxAx_oo = ("gAxAx_oo", true)
    rxIxI_vv = ("rxIxI_vv", true)
    gxIxI_vv = ("gxIxI_vv", true)
    rAxAx_oo = ("rAxAx_oo", true)
    FAx_v = ("FAx_v", true)
    tAIxI_v = ("tAIxI_v", true)
    FxI_o = ("FxI_o", true)
    tAIAx_o = ("tAIAx_o", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    txIxI_vv = ("txIxI_vv", true)
    tAxAx_oo = ("tAxAx_oo", true)
    gAIxx_ov = ("gAIxx_ov", true)
    uAIxx_vo = ("uAIxx_vo", true)
    gAxAx_vv = ("gAxAx_vv", true)
    t_vovo = ("t_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAxxI_vo = ("gAxxI_vo", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    gxIxI_oo = ("gxIxI_oo", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    txIxx_vvo = ("txIxx_vvo", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    uxIxx_vvo = ("uxIxx_vvo", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    txxxI_vov = ("txxxI_vov", true)
    update_code!(func, ein"bjck,->bjck", 2//1, [L_vovo, rAIAI])
    update_code!(func, ein",bjck->bjck", 4//1, [gAIAI, r_vovo])
    update_code!(func, ein",bkcj->bjck", -2//1, [gAIAI, r_vovo])
    update_code!(func, ein"jk,bc->bjck", 2//1, [gAxAx_oo, rxIxI_vv])
    update_code!(func, ein"bc,jk->bjck", 2//1, [gxIxI_vv, rAxAx_oo])
    update_code!(func, ein"d,bjck,d->bjck", 8//1, [FAx_v, r_vovo, tAIxI_v])
    update_code!(func, ein"d,bkcj,d->bjck", -4//1, [FAx_v, r_vovo, tAIxI_v])
    update_code!(func, ein"l,bjck,l->bjck", -8//1, [FxI_o, r_vovo, tAIAx_o])
    update_code!(func, ein"l,bkcj,l->bjck", 4//1, [FxI_o, r_vovo, tAIAx_o])
    update_code!(func, ein"bdce,,djek->bjck", 2//1, [g_vvvv, rAIAI, u_vovo])
    update_code!(func, ein"ljmk,,blcm->bjck", 2//1, [g_oooo, rAIAI, u_vovo])
    update_code!(func, ein"bdce,jk,de->bjck", 2//1, [g_vvvv, rAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmk,bc,lm->bjck", 2//1, [g_oooo, rxIxI_vv, tAxAx_oo])
    update_code!(func, ein"ld,bjck,dl->bjck", 8//1, [gAIxx_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bkcj,dl->bjck", -4//1, [gAIxx_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"de,bjck,de->bjck", 4//1, [gAxAx_vv, r_vovo, txIxI_vv])
    update_code!(func, ein"de,bkcj,de->bjck", -2//1, [gAxAx_vv, r_vovo, txIxI_vv])
    update_code!(func, ein"de,bc,djek->bjck", 2//1, [gAxAx_vv, rxIxI_vv, t_vovo])
    update_code!(func, ein"dl,bjck,dl->bjck", -8//1, [gAxxI_vo, r_vovo, tAIxx_vo])
    update_code!(func, ein"dl,bkcj,dl->bjck", 4//1, [gAxxI_vo, r_vovo, tAIxx_vo])
    update_code!(func, ein"dl,bjck,ld->bjck", -8//1, [gAxxI_vo, r_vovo, tAxxI_ov])
    update_code!(func, ein"dl,bkcj,ld->bjck", 4//1, [gAxxI_vo, r_vovo, tAxxI_ov])
    update_code!(func, ein"lm,bjck,lm->bjck", 4//1, [gxIxI_oo, r_vovo, tAxAx_oo])
    update_code!(func, ein"lm,bkcj,lm->bjck", -2//1, [gxIxI_oo, r_vovo, tAxAx_oo])
    update_code!(func, ein"lm,jk,blcm->bjck", 2//1, [gxIxI_oo, rAxAx_oo, t_vovo])
    update_code!(func, ein"ldme,bjck,dl,em->bjck", 8//1, [L_ovov, r_vovo, tAIxx_vo, tAIxx_vo])
    update_code!(func, ein"ldme,bkcj,dl,em->bjck", -4//1, [L_ovov, r_vovo, tAIxx_vo, tAIxx_vo])
    update_code!(func, ein"ldme,blcm,dj,ek->bjck", 4//1, [L_ovov, r_vovo, tAIxx_vo, tAIxx_vo])
    update_code!(func, ein"ldme,djek,bl,cm->bjck", 4//1, [L_ovov, r_vovo, tAIxx_vo, tAIxx_vo])
    update_code!(func, ein"ldme,bjck,dl,me->bjck", -8//1, [L_ovov, r_vovo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ldme,bkcj,dl,me->bjck", 4//1, [L_ovov, r_vovo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ldme,,bjdl,ckem->bjck", 8//1, [L_ovov, rAIAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,,bkdl,cjem->bjck", -4//1, [L_ovov, rAIAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,,bldj,cmek->bjck", 2//1, [L_ovov, rAIAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,,blek,cmdj->bjck", 2//1, [L_ovov, rAIAI, t_vovo, t_vovo])
    update_code!(func, ein"ldme,jk,bdl,cem->bjck", 4//1, [L_ovov, rAxAx_oo, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"ldme,bc,jdl,kem->bjck", 4//1, [L_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,bjck,l,dem->bjck", -8//1, [g_ovov, r_vovo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ldme,bkcj,l,dem->bjck", 4//1, [g_ovov, r_vovo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ldme,bjck,d,lem->bjck", -8//1, [g_ovov, r_vovo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ldme,bkcj,d,lem->bjck", 4//1, [g_ovov, r_vovo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ldme,bjck,lm,de->bjck", 4//1, [g_ovov, r_vovo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ldme,bkcj,lm,de->bjck", -2//1, [g_ovov, r_vovo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ldme,bjck,ld,me->bjck", 4//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,bjck,le,md->bjck", 4//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,bkcj,ld,me->bjck", -2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,bkcj,le,md->bjck", -2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,blcm,jd,ke->bjck", 2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,blcm,je,kd->bjck", 2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,djek,lb,mc->bjck", 2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,djek,lc,mb->bjck", 2//1, [g_ovov, r_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,,djek,blcm->bjck", 2//1, [g_ovov, rAIAI, t_vovo, u_vovo])
    update_code!(func, ein"ldme,jk,blcm,de->bjck", 2//1, [g_ovov, rAxAx_oo, t_vovo, txIxI_vv])
    update_code!(func, ein"ldme,lm,bdj,cek->bjck", 2//1, [g_ovov, rAxAx_oo, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"ldme,lm,bdk,cej->bjck", 2//1, [g_ovov, rAxAx_oo, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"ldme,jk,bld,cme->bjck", 2//1, [g_ovov, rAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,jk,ble,cmd->bjck", 2//1, [g_ovov, rAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,lm,bjd,cke->bjck", 8//1, [g_ovov, rAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,lm,bkd,cje->bjck", -4//1, [g_ovov, rAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,bc,djek,lm->bjck", 2//1, [g_ovov, rxIxI_vv, t_vovo, tAxAx_oo])
    update_code!(func, ein"ldme,bc,ldj,mek->bjck", 2//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,bc,lej,mdk->bjck", 2//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,de,jbl,kcm->bjck", 2//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,de,jcl,kbm->bjck", 2//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,de,lbj,mck->bjck", 8//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"ldme,de,lbk,mcj->bjck", -4//1, [g_ovov, rxIxI_vv, tAxxx_ovo, tAxxx_ovo])
    finalize_eT_function(func, "mu_4_H_nu_1_ss", "doublet_ccsd")
end

println(io, s)
end
