include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_4_H_nu_1_s.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    L_vooo = ("L_vooo", true)
    rAI = ("rAI", true)
    uAIxx_vo = ("uAIxx_vo", true)
    rxI_v = ("rxI_v", true)
    tAIAx_o = ("tAIAx_o", true)
    LAIxx_vv = ("LAIxx_vv", true)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAIxx_oo = ("LAIxx_oo", true)
    LAxxx_vvo = ("LAxxx_vvo", true)
    r_vo = ("r_vo", true)
    tAIxI_v = ("tAIxI_v", true)
    uxxxI_vov = ("uxxxI_vov", true)
    rAx_o = ("rAx_o", true)
    txIxI_vv = ("txIxI_vv", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    LxxxI_voo = ("LxxxI_voo", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    tAxAx_oo = ("tAxAx_oo", true)
    g_vovv = ("g_vovv", true)
    gAIAx_v = ("gAIAx_v", true)
    gAIxI_o = ("gAIxI_o", true)
    gAIxx_vv = ("gAIxx_vv", true)
    gAIxx_oo = ("gAIxx_oo", true)
    uxIxx_vvo = ("uxIxx_vvo", true)
    gAxAx_ov = ("gAxAx_ov", true)
    txIxx_vvo = ("txIxx_vvo", true)
    txxxI_vov = ("txxxI_vov", true)
    gAxxI_oo = ("gAxxI_oo", true)
    gAxxI_vv = ("gAxxI_vv", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    gAxxx_ovv = ("gAxxx_ovv", true)
    gAxxx_vvo = ("gAxxx_vvo", true)
    gAxxx_ooo = ("gAxxx_ooo", true)
    gxIxI_vo = ("gxIxI_vo", true)
    gxIxx_vvv = ("gxIxx_vvv", true)
    gxIxx_voo = ("gxIxx_voo", true)
    gxxxI_voo = ("gxxxI_voo", true)
    F_ov = ("wf%fock_ia", false)
    L_vvov = ("L_vvov", true)
    L_ooov = ("L_ooov", true)
    LAxxx_vov = ("LAxxx_vov", true)
    LxIxx_oov = ("LxIxx_oov", true)
    g_vvov = ("g_vvov", true)
    g_ooov = ("g_ooov", true)
    gAxxx_vov = ("gAxxx_vov", true)
    t_vovo = ("t_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gxIxx_oov = ("gxIxx_oov", true)
    update_code!(func, ein"bjlk,,cl->bjck", -2//1, [L_vooo, rAI, uAIxx_vo])
    update_code!(func, ein"bjlk,c,l->bjck", 2//1, [L_vooo, rxI_v, tAIAx_o])
    update_code!(func, ein"bd,,ckdj->bjck", 2//1, [LAIxx_vv, rAI, u_vovo])
    update_code!(func, ein"lj,,blck->bjck", -2//1, [LAIxx_oo, rAI, u_vovo])
    update_code!(func, ein"dbj,ck,d->bjck", 4//1, [LAxxx_vvo, r_vo, tAIxI_v])
    update_code!(func, ein"dbj,,ckd->bjck", 2//1, [LAxxx_vvo, rAI, uxxxI_vov])
    update_code!(func, ein"dbj,k,cd->bjck", -2//1, [LAxxx_vvo, rAx_o, txIxI_vv])
    update_code!(func, ein"dbj,c,dk->bjck", -2//1, [LAxxx_vvo, rxI_v, tAIxx_vo])
    update_code!(func, ein"dbj,c,kd->bjck", -2//1, [LAxxx_vvo, rxI_v, tAxxI_ov])
    update_code!(func, ein"bjl,ck,l->bjck", -4//1, [LxxxI_voo, r_vo, tAIAx_o])
    update_code!(func, ein"bkl,cj,l->bjck", 2//1, [LxxxI_voo, r_vo, tAIAx_o])
    update_code!(func, ein"bjl,,lck->bjck", -2//1, [LxxxI_voo, rAI, uAxxx_ovo])
    update_code!(func, ein"bjl,k,cl->bjck", 2//1, [LxxxI_voo, rAx_o, tAIxx_vo])
    update_code!(func, ein"bjl,k,lc->bjck", 2//1, [LxxxI_voo, rAx_o, tAxxI_ov])
    update_code!(func, ein"bjl,c,kl->bjck", 2//1, [LxxxI_voo, rxI_v, tAxAx_oo])
    update_code!(func, ein"bjcd,,dk->bjck", 4//1, [g_vovv, rAI, uAIxx_vo])
    update_code!(func, ein"bkcd,,dj->bjck", -2//1, [g_vovv, rAI, uAIxx_vo])
    update_code!(func, ein"bjcd,k,d->bjck", -4//1, [g_vovv, rAx_o, tAIxI_v])
    update_code!(func, ein"bkcd,j,d->bjck", 2//1, [g_vovv, rAx_o, tAIxI_v])
    update_code!(func, ein"d,bj,ckd->bjck", 4//1, [gAIAx_v, r_vo, uxxxI_vov])
    update_code!(func, ein"d,bk,cjd->bjck", -2//1, [gAIAx_v, r_vo, uxxxI_vov])
    update_code!(func, ein"d,b,ckdj->bjck", -2//1, [gAIAx_v, rxI_v, u_vovo])
    update_code!(func, ein"l,bj,lck->bjck", -4//1, [gAIxI_o, r_vo, uAxxx_ovo])
    update_code!(func, ein"l,bk,lcj->bjck", 2//1, [gAIxI_o, r_vo, uAxxx_ovo])
    update_code!(func, ein"l,j,blck->bjck", 2//1, [gAIxI_o, rAx_o, u_vovo])
    update_code!(func, ein"bd,cj,dk->bjck", -2//1, [gAIxx_vv, r_vo, uAIxx_vo])
    update_code!(func, ein"bd,ck,dj->bjck", 4//1, [gAIxx_vv, r_vo, uAIxx_vo])
    update_code!(func, ein"lj,bk,cl->bjck", 2//1, [gAIxx_oo, r_vo, uAIxx_vo])
    update_code!(func, ein"lj,ck,bl->bjck", -4//1, [gAIxx_oo, r_vo, uAIxx_vo])
    update_code!(func, ein"bd,k,cdj->bjck", -2//1, [gAIxx_vv, rAx_o, uxIxx_vvo])
    update_code!(func, ein"bd,j,ckd->bjck", -2//1, [gAIxx_vv, rAx_o, uxxxI_vov])
    update_code!(func, ein"lj,k,blc->bjck", 2//1, [gAIxx_oo, rAx_o, uxxxI_vov])
    update_code!(func, ein"bd,c,kdj->bjck", -2//1, [gAIxx_vv, rxI_v, uAxxx_ovo])
    update_code!(func, ein"lj,b,lck->bjck", 2//1, [gAIxx_oo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"lj,c,kbl->bjck", 2//1, [gAIxx_oo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"jd,bk,cd->bjck", 2//1, [gAxAx_ov, r_vo, txIxI_vv])
    update_code!(func, ein"jd,ck,bd->bjck", -4//1, [gAxAx_ov, r_vo, txIxI_vv])
    update_code!(func, ein"jd,c,bdk->bjck", 2//1, [gAxAx_ov, rxI_v, txIxx_vvo])
    update_code!(func, ein"jd,c,bkd->bjck", 2//1, [gAxAx_ov, rxI_v, txxxI_vov])
    update_code!(func, ein"jd,b,ckd->bjck", -2//1, [gAxAx_ov, rxI_v, uxxxI_vov])
    update_code!(func, ein"jl,bk,cl->bjck", -2//1, [gAxxI_oo, r_vo, tAIxx_vo])
    update_code!(func, ein"jl,ck,bl->bjck", 4//1, [gAxxI_oo, r_vo, tAIxx_vo])
    update_code!(func, ein"db,cj,dk->bjck", 2//1, [gAxxI_vv, r_vo, tAIxx_vo])
    update_code!(func, ein"db,ck,dj->bjck", -4//1, [gAxxI_vv, r_vo, tAIxx_vo])
    update_code!(func, ein"jl,bk,lc->bjck", -2//1, [gAxxI_oo, r_vo, tAxxI_ov])
    update_code!(func, ein"jl,ck,lb->bjck", 4//1, [gAxxI_oo, r_vo, tAxxI_ov])
    update_code!(func, ein"db,cj,kd->bjck", 2//1, [gAxxI_vv, r_vo, tAxxI_ov])
    update_code!(func, ein"db,ck,jd->bjck", -4//1, [gAxxI_vv, r_vo, tAxxI_ov])
    update_code!(func, ein"jl,k,bcl->bjck", -2//1, [gAxxI_oo, rAx_o, txIxx_vvo])
    update_code!(func, ein"db,k,cdj->bjck", 2//1, [gAxxI_vv, rAx_o, txIxx_vvo])
    update_code!(func, ein"jl,k,blc->bjck", -2//1, [gAxxI_oo, rAx_o, txxxI_vov])
    update_code!(func, ein"db,k,cjd->bjck", 2//1, [gAxxI_vv, rAx_o, txxxI_vov])
    update_code!(func, ein"db,j,ckd->bjck", -2//1, [gAxxI_vv, rAx_o, uxxxI_vov])
    update_code!(func, ein"jl,c,kbl->bjck", -2//1, [gAxxI_oo, rxI_v, tAxxx_ovo])
    update_code!(func, ein"jl,c,lbk->bjck", -2//1, [gAxxI_oo, rxI_v, tAxxx_ovo])
    update_code!(func, ein"db,c,jdk->bjck", 2//1, [gAxxI_vv, rxI_v, tAxxx_ovo])
    update_code!(func, ein"db,c,kdj->bjck", 2//1, [gAxxI_vv, rxI_v, tAxxx_ovo])
    update_code!(func, ein"jl,b,lck->bjck", 2//1, [gAxxI_oo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"jcd,bk,d->bjck", 2//1, [gAxxx_ovv, r_vo, tAIxI_v])
    update_code!(func, ein"dbk,cj,d->bjck", -4//1, [gAxxx_vvo, r_vo, tAIxI_v])
    update_code!(func, ein"jcd,,bdk->bjck", -2//1, [gAxxx_ovv, rAI, uxIxx_vvo])
    update_code!(func, ein"jlk,,bcl->bjck", 2//1, [gAxxx_ooo, rAI, uxIxx_vvo])
    update_code!(func, ein"dbk,,cjd->bjck", -2//1, [gAxxx_vvo, rAI, uxxxI_vov])
    update_code!(func, ein"jcd,k,bd->bjck", 2//1, [gAxxx_ovv, rAx_o, txIxI_vv])
    update_code!(func, ein"dbk,j,cd->bjck", 2//1, [gAxxx_vvo, rAx_o, txIxI_vv])
    update_code!(func, ein"jlk,c,bl->bjck", -2//1, [gAxxx_ooo, rxI_v, tAIxx_vo])
    update_code!(func, ein"dbk,c,dj->bjck", 2//1, [gAxxx_vvo, rxI_v, tAIxx_vo])
    update_code!(func, ein"jlk,c,lb->bjck", -2//1, [gAxxx_ooo, rxI_v, tAxxI_ov])
    update_code!(func, ein"dbk,c,jd->bjck", 2//1, [gAxxx_vvo, rxI_v, tAxxI_ov])
    update_code!(func, ein"jcd,b,dk->bjck", -2//1, [gAxxx_ovv, rxI_v, uAIxx_vo])
    update_code!(func, ein"jlk,b,cl->bjck", 2//1, [gAxxx_ooo, rxI_v, uAIxx_vo])
    update_code!(func, ein"bl,cj,kl->bjck", -2//1, [gxIxI_vo, r_vo, tAxAx_oo])
    update_code!(func, ein"bl,ck,jl->bjck", 4//1, [gxIxI_vo, r_vo, tAxAx_oo])
    update_code!(func, ein"bl,k,jcl->bjck", -2//1, [gxIxI_vo, rAx_o, tAxxx_ovo])
    update_code!(func, ein"bl,k,lcj->bjck", -2//1, [gxIxI_vo, rAx_o, tAxxx_ovo])
    update_code!(func, ein"bl,j,lck->bjck", 2//1, [gxIxI_vo, rAx_o, uAxxx_ovo])
    update_code!(func, ein"bcd,,jdk->bjck", -2//1, [gxIxx_vvv, rAI, uAxxx_ovo])
    update_code!(func, ein"blk,,jcl->bjck", 2//1, [gxIxx_voo, rAI, uAxxx_ovo])
    update_code!(func, ein"bcd,k,dj->bjck", 2//1, [gxIxx_vvv, rAx_o, tAIxx_vo])
    update_code!(func, ein"bcd,k,jd->bjck", 2//1, [gxIxx_vvv, rAx_o, tAxxI_ov])
    update_code!(func, ein"bcd,j,dk->bjck", -2//1, [gxIxx_vvv, rAx_o, uAIxx_vo])
    update_code!(func, ein"blk,j,cl->bjck", 2//1, [gxIxx_voo, rAx_o, uAIxx_vo])
    update_code!(func, ein"blk,c,jl->bjck", -2//1, [gxIxx_voo, rxI_v, tAxAx_oo])
    update_code!(func, ein"bkl,,lcj->bjck", 2//1, [gxxxI_voo, rAI, uAxxx_ovo])
    update_code!(func, ein"bkl,j,cl->bjck", -2//1, [gxxxI_voo, rAx_o, tAIxx_vo])
    update_code!(func, ein"bkl,j,lc->bjck", -2//1, [gxxxI_voo, rAx_o, tAxxI_ov])
    update_code!(func, ein"bkl,c,jl->bjck", -2//1, [gxxxI_voo, rxI_v, tAxAx_oo])
    update_code!(func, ein"ld,bj,l,ckd->bjck", -4//1, [F_ov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ld,bk,l,cjd->bjck", 2//1, [F_ov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ld,bj,d,lck->bjck", -4//1, [F_ov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ld,bk,d,lcj->bjck", 2//1, [F_ov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ld,bj,cl,kd->bjck", 4//1, [F_ov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ld,bk,cl,jd->bjck", -2//1, [F_ov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ld,bj,dk,cl->bjck", -4//1, [F_ov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ld,bk,dj,cl->bjck", 2//1, [F_ov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ld,bj,kl,cd->bjck", 4//1, [F_ov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ld,bk,jl,cd->bjck", -2//1, [F_ov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ld,bj,kd,lc->bjck", 4//1, [F_ov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ld,bk,jd,lc->bjck", -2//1, [F_ov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ld,,jcl,bdk->bjck", 2//1, [F_ov, rAI, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,,jdk,bcl->bjck", 2//1, [F_ov, rAI, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ld,,lbk,cjd->bjck", 2//1, [F_ov, rAI, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ld,,blck,dj->bjck", -2//1, [F_ov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ld,,ckdj,bl->bjck", -2//1, [F_ov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ld,,lbj,ckd->bjck", -2//1, [F_ov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ld,j,d,blck->bjck", 2//1, [F_ov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"ld,j,cl,bkd->bjck", -2//1, [F_ov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"ld,j,dk,blc->bjck", -2//1, [F_ov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"ld,j,bl,ckd->bjck", 2//1, [F_ov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ld,j,kd,blc->bjck", -2//1, [F_ov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"ld,j,lc,bkd->bjck", -2//1, [F_ov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"ld,j,lb,ckd->bjck", 2//1, [F_ov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"ld,j,kbl,cd->bjck", -2//1, [F_ov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ld,j,lbk,cd->bjck", -2//1, [F_ov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ld,j,bd,lck->bjck", 2//1, [F_ov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ld,j,bcl,dk->bjck", 2//1, [F_ov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ld,j,bdk,cl->bjck", 2//1, [F_ov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ld,b,l,ckdj->bjck", 2//1, [F_ov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"ld,b,cl,kdj->bjck", -2//1, [F_ov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ld,b,dk,lcj->bjck", -2//1, [F_ov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ld,b,dj,lck->bjck", 2//1, [F_ov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ld,b,kl,cdj->bjck", -2//1, [F_ov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"ld,b,kl,cjd->bjck", -2//1, [F_ov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"ld,b,jl,ckd->bjck", 2//1, [F_ov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"ld,b,kd,lcj->bjck", -2//1, [F_ov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ld,b,lc,kdj->bjck", -2//1, [F_ov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ld,b,jd,lck->bjck", 2//1, [F_ov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ld,b,jcl,dk->bjck", 2//1, [F_ov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ld,b,jdk,cl->bjck", 2//1, [F_ov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,dj,l,cke->bjck", -2//1, [L_vvov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ljmd,bl,m,ckd->bjck", 2//1, [L_ooov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bdle,dj,e,lck->bjck", -2//1, [L_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmd,bl,d,mck->bjck", 2//1, [L_ooov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,dj,cl,ke->bjck", 2//1, [L_vvov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmd,bl,cm,kd->bjck", -2//1, [L_ooov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdle,dj,ek,cl->bjck", -2//1, [L_vvov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,bl,dk,cm->bjck", 2//1, [L_ooov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,dj,kl,ce->bjck", 2//1, [L_vvov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmd,bl,km,cd->bjck", -2//1, [L_ooov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdle,dj,ke,lc->bjck", 2//1, [L_vvov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmd,bl,kd,mc->bjck", -2//1, [L_ooov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdle,,ckdj,el->bjck", 2//1, [L_vvov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,,ckel,dj->bjck", 2//1, [L_vvov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,,blck,dm->bjck", -2//1, [L_ooov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,,ckdm,bl->bjck", -2//1, [L_ooov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,j,d,ckel->bjck", -2//1, [L_vvov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"bdle,l,e,ckdj->bjck", -2//1, [L_vvov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"ljmd,m,d,blck->bjck", 2//1, [L_ooov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"bdle,e,l,ckdj->bjck", -2//1, [L_vvov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"ljmd,b,l,ckdm->bjck", 2//1, [L_ooov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"ljmd,d,m,blck->bjck", 2//1, [L_ooov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"dle,bj,d,ckel->bjck", 4//1, [LAxxx_vov, r_vo, tAIxI_v, u_vovo])
    update_code!(func, ein"dle,bk,d,cjel->bjck", -2//1, [LAxxx_vov, r_vo, tAIxI_v, u_vovo])
    update_code!(func, ein"dle,bl,d,ckej->bjck", -2//1, [LAxxx_vov, r_vo, tAIxI_v, u_vovo])
    update_code!(func, ein"dle,ej,d,blck->bjck", -2//1, [LAxxx_vov, r_vo, tAIxI_v, u_vovo])
    update_code!(func, ein"dle,,bel,ckdj->bjck", -2//1, [LAxxx_vov, rAI, txIxx_vvo, u_vovo])
    update_code!(func, ein"dle,,cld,bjek->bjck", -2//1, [LAxxx_vov, rAI, txxxI_vov, u_vovo])
    update_code!(func, ein"dle,j,bd,ckel->bjck", -2//1, [LAxxx_vov, rAx_o, txIxI_vv, u_vovo])
    update_code!(func, ein"dle,b,dj,ckel->bjck", -2//1, [LAxxx_vov, rxI_v, tAIxx_vo, u_vovo])
    update_code!(func, ein"dle,b,jd,ckel->bjck", -2//1, [LAxxx_vov, rxI_v, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,bj,l,ckdm->bjck", -4//1, [LxIxx_oov, r_vo, tAIAx_o, u_vovo])
    update_code!(func, ein"lmd,bk,l,cjdm->bjck", 2//1, [LxIxx_oov, r_vo, tAIAx_o, u_vovo])
    update_code!(func, ein"lmd,bm,l,ckdj->bjck", 2//1, [LxIxx_oov, r_vo, tAIAx_o, u_vovo])
    update_code!(func, ein"lmd,dj,l,bmck->bjck", 2//1, [LxIxx_oov, r_vo, tAIAx_o, u_vovo])
    update_code!(func, ein"lmd,,lbk,cjdm->bjck", 2//1, [LxIxx_oov, rAI, tAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,,ckdm,lbj->bjck", -2//1, [LxIxx_oov, rAI, u_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bl,ckdm->bjck", 2//1, [LxIxx_oov, rAx_o, tAIxx_vo, u_vovo])
    update_code!(func, ein"lmd,j,lb,ckdm->bjck", 2//1, [LxIxx_oov, rAx_o, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,b,jl,ckdm->bjck", 2//1, [LxIxx_oov, rxI_v, tAxAx_oo, u_vovo])
    update_code!(func, ein"bdle,ek,l,cdj->bjck", 2//1, [g_vvov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmd,bk,l,cdm->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmd,ck,l,bdm->bjck", 4//1, [g_ooov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmd,cm,l,bdk->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmd,dk,l,bcm->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"bdle,cj,l,dke->bjck", 2//1, [g_vvov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bdle,ck,l,dje->bjck", -4//1, [g_vvov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bdle,dk,l,cje->bjck", 2//1, [g_vvov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ljmd,bk,m,cld->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ljmd,ck,m,bld->bjck", 4//1, [g_ooov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ljmd,cl,m,bkd->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ljmd,dk,m,blc->bjck", -2//1, [g_ooov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bdle,cj,d,kel->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,cj,e,ldk->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,ck,d,jel->bjck", -4//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,ck,e,ldj->bjck", -4//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,cl,d,jek->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,cl,e,kdj->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,dk,e,lcj->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,ek,d,jcl->bjck", 2//1, [g_vvov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmd,bk,d,mcl->bjck", -2//1, [g_ooov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmd,ck,d,mbl->bjck", 4//1, [g_ooov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmd,cl,d,mbk->bjck", -2//1, [g_ooov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ljmd,cm,d,kbl->bjck", -2//1, [g_ooov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdle,cj,dl,ke->bjck", -2//1, [g_vvov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdle,ck,dl,je->bjck", 4//1, [g_vvov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdle,cl,dk,je->bjck", -2//1, [g_vvov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdle,dk,cl,je->bjck", -2//1, [g_vvov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmd,bk,cm,ld->bjck", 2//1, [g_ooov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmd,ck,bm,ld->bjck", -4//1, [g_ooov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmd,cl,bm,kd->bjck", 2//1, [g_ooov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmd,dk,bm,lc->bjck", 2//1, [g_ooov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdle,cj,ek,dl->bjck", 2//1, [g_vvov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,ck,ej,dl->bjck", -4//1, [g_vvov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,cl,ej,dk->bjck", 2//1, [g_vvov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,dk,ej,cl->bjck", 2//1, [g_vvov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,bk,dl,cm->bjck", -2//1, [g_ooov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,ck,dl,bm->bjck", 4//1, [g_ooov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,cl,dk,bm->bjck", -2//1, [g_ooov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,dk,cl,bm->bjck", -2//1, [g_ooov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,cj,kl,de->bjck", -2//1, [g_vvov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdle,ck,jl,de->bjck", 4//1, [g_vvov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdle,dk,jl,ce->bjck", -2//1, [g_vvov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdle,ek,jl,cd->bjck", -2//1, [g_vvov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmd,bk,lm,cd->bjck", 2//1, [g_ooov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmd,ck,lm,bd->bjck", -4//1, [g_ooov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmd,cl,km,bd->bjck", 2//1, [g_ooov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmd,cm,kl,bd->bjck", 2//1, [g_ooov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdle,cj,ke,ld->bjck", -2//1, [g_vvov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdle,ck,je,ld->bjck", 4//1, [g_vvov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdle,cl,je,kd->bjck", -2//1, [g_vvov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdle,dk,je,lc->bjck", -2//1, [g_vvov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmd,bk,ld,mc->bjck", 2//1, [g_ooov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmd,ck,ld,mb->bjck", -4//1, [g_ooov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmd,cl,kd,mb->bjck", 2//1, [g_ooov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmd,dk,lc,mb->bjck", 2//1, [g_ooov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdle,cj,dk,el->bjck", -2//1, [g_vvov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,ck,dj,el->bjck", 4//1, [g_vvov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,cl,dj,ek->bjck", -2//1, [g_vvov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,ek,cl,dj->bjck", -2//1, [g_vvov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,bk,cl,dm->bjck", 2//1, [g_ooov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,ck,bl,dm->bjck", -4//1, [g_ooov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,cm,bl,dk->bjck", 2//1, [g_ooov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmd,dk,bl,cm->bjck", 2//1, [g_ooov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdle,,cdl,kej->bjck", 2//1, [g_vvov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,,cej,kdl->bjck", 2//1, [g_vvov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,,dek,jcl->bjck", 2//1, [g_vvov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,,bcm,ldk->bjck", -2//1, [g_ooov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,,bdk,lcm->bjck", -2//1, [g_ooov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ljmd,,cdl,kbm->bjck", -2//1, [g_ooov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"bdle,,cje,ldk->bjck", 2//1, [g_vvov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,,cld,jek->bjck", 2//1, [g_vvov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,,dke,lcj->bjck", 2//1, [g_vvov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,,bkd,mcl->bjck", -2//1, [g_ooov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,,bmc,kdl->bjck", -2//1, [g_ooov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ljmd,,cld,mbk->bjck", -2//1, [g_ooov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"bdle,,cjel,dk->bjck", -2//1, [g_vvov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,,cldj,ek->bjck", -2//1, [g_vvov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,,djek,cl->bjck", -2//1, [g_vvov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,,bkdm,cl->bjck", 2//1, [g_ooov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,,blcm,dk->bjck", 2//1, [g_ooov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"ljmd,,bldk,cm->bjck", 2//1, [g_ooov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"bdle,,kdj,cel->bjck", -2//1, [g_vvov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,,kel,cdj->bjck", -2//1, [g_vvov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,,kbl,cdm->bjck", 2//1, [g_ooov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ljmd,,lck,bdm->bjck", 2//1, [g_ooov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"bdle,,jel,ckd->bjck", -2//1, [g_vvov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,,lck,dje->bjck", -2//1, [g_vvov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,,ldj,cke->bjck", -2//1, [g_vvov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,,kdm,blc->bjck", 2//1, [g_ooov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,,mbl,ckd->bjck", 2//1, [g_ooov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ljmd,,mck,bld->bjck", 2//1, [g_ooov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"bdle,k,d,cjel->bjck", 2//1, [g_vvov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"bdle,k,e,cldj->bjck", 2//1, [g_vvov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"ljmd,k,d,blcm->bjck", -2//1, [g_ooov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"bdle,j,ek,cdl->bjck", -2//1, [g_vvov, rAx_o, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"bdle,l,dk,cej->bjck", -2//1, [g_vvov, rAx_o, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"ljmd,k,dl,bcm->bjck", 2//1, [g_ooov, rAx_o, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"ljmd,m,cl,bdk->bjck", 2//1, [g_ooov, rAx_o, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"bdle,j,cl,dke->bjck", -2//1, [g_vvov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"bdle,k,dl,cje->bjck", -2//1, [g_vvov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"bdle,k,ej,cld->bjck", -2//1, [g_vvov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"ljmd,k,bm,cld->bjck", 2//1, [g_ooov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"ljmd,l,cm,bkd->bjck", 2//1, [g_ooov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"ljmd,l,dk,bmc->bjck", 2//1, [g_ooov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"bdle,j,dk,cel->bjck", 2//1, [g_vvov, rAx_o, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"bdle,l,ek,cdj->bjck", 2//1, [g_vvov, rAx_o, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"ljmd,k,cl,bdm->bjck", -2//1, [g_ooov, rAx_o, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"bdle,j,dl,cke->bjck", 2//1, [g_vvov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"bdle,k,cl,dje->bjck", 2//1, [g_vvov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"bdle,l,ej,ckd->bjck", 2//1, [g_vvov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ljmd,k,cm,bld->bjck", -2//1, [g_ooov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ljmd,l,bm,ckd->bjck", -2//1, [g_ooov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ljmd,m,dk,blc->bjck", -2//1, [g_ooov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"bdle,j,ke,cdl->bjck", -2//1, [g_vvov, rAx_o, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"bdle,l,kd,cej->bjck", -2//1, [g_vvov, rAx_o, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"ljmd,k,ld,bcm->bjck", 2//1, [g_ooov, rAx_o, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"ljmd,m,lc,bdk->bjck", 2//1, [g_ooov, rAx_o, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"bdle,j,lc,dke->bjck", -2//1, [g_vvov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"bdle,k,je,cld->bjck", -2//1, [g_vvov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"bdle,k,ld,cje->bjck", -2//1, [g_vvov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"ljmd,k,mb,cld->bjck", 2//1, [g_ooov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"ljmd,l,kd,bmc->bjck", 2//1, [g_ooov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"ljmd,l,mc,bkd->bjck", 2//1, [g_ooov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"bdle,j,kd,cel->bjck", 2//1, [g_vvov, rAx_o, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"bdle,l,ke,cdj->bjck", 2//1, [g_vvov, rAx_o, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"ljmd,k,lc,bdm->bjck", -2//1, [g_ooov, rAx_o, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"bdle,j,ld,cke->bjck", 2//1, [g_vvov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"bdle,k,lc,dje->bjck", 2//1, [g_vvov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"bdle,l,je,ckd->bjck", 2//1, [g_vvov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"ljmd,k,mc,bld->bjck", -2//1, [g_ooov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"ljmd,l,mb,ckd->bjck", -2//1, [g_ooov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"ljmd,m,kd,blc->bjck", -2//1, [g_ooov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"bdle,j,kdl,ce->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,j,ldk,ce->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,k,jcl,de->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,k,lcj,de->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,l,jek,cd->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,l,kej,cd->bjck", -2//1, [g_vvov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ljmd,k,lcm,bd->bjck", 2//1, [g_ooov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ljmd,k,mcl,bd->bjck", 2//1, [g_ooov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ljmd,l,kbm,cd->bjck", 2//1, [g_ooov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ljmd,l,mbk,cd->bjck", 2//1, [g_ooov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"bdle,j,cd,kel->bjck", 2//1, [g_vvov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"bdle,j,de,lck->bjck", 2//1, [g_vvov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"bdle,k,cd,jel->bjck", 2//1, [g_vvov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"bdle,k,ce,ldj->bjck", 2//1, [g_vvov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"bdle,l,ce,kdj->bjck", 2//1, [g_vvov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ljmd,k,cd,mbl->bjck", -2//1, [g_ooov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ljmd,l,bd,mck->bjck", -2//1, [g_ooov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ljmd,m,bd,lck->bjck", -2//1, [g_ooov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ljmd,m,cd,kbl->bjck", -2//1, [g_ooov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"bdle,j,dek,cl->bjck", 2//1, [g_vvov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"bdle,k,cdl,ej->bjck", 2//1, [g_vvov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"bdle,k,cej,dl->bjck", 2//1, [g_vvov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ljmd,k,cdl,bm->bjck", -2//1, [g_ooov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ljmd,l,bcm,dk->bjck", -2//1, [g_ooov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ljmd,l,bdk,cm->bjck", -2//1, [g_ooov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"bdle,j,cld,ek->bjck", 2//1, [g_vvov, rAx_o, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"bdle,l,cje,dk->bjck", 2//1, [g_vvov, rAx_o, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"ljmd,k,bmc,dl->bjck", -2//1, [g_ooov, rAx_o, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"ljmd,m,bkd,cl->bjck", -2//1, [g_ooov, rAx_o, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"bdle,k,dj,cel->bjck", -2//1, [g_vvov, rAx_o, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"bdle,k,el,cdj->bjck", -2//1, [g_vvov, rAx_o, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"ljmd,k,bl,cdm->bjck", 2//1, [g_ooov, rAx_o, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"bdle,j,el,ckd->bjck", -2//1, [g_vvov, rAx_o, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"bdle,l,dj,cke->bjck", -2//1, [g_vvov, rAx_o, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ljmd,k,dm,blc->bjck", 2//1, [g_ooov, rAx_o, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ljmd,m,bl,ckd->bjck", 2//1, [g_ooov, rAx_o, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"bdle,c,l,djek->bjck", 2//1, [g_vvov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"ljmd,c,l,bkdm->bjck", -2//1, [g_ooov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"ljmd,c,m,bldk->bjck", -2//1, [g_ooov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"bdle,c,dl,jek->bjck", -2//1, [g_vvov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdle,c,ej,ldk->bjck", -2//1, [g_vvov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdle,d,cl,kej->bjck", -2//1, [g_vvov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdle,d,ek,lcj->bjck", -2//1, [g_vvov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdle,e,dk,jcl->bjck", -2//1, [g_vvov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ljmd,b,cm,kdl->bjck", 2//1, [g_ooov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ljmd,b,dk,mcl->bjck", 2//1, [g_ooov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ljmd,c,bm,ldk->bjck", 2//1, [g_ooov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ljmd,c,dl,mbk->bjck", 2//1, [g_ooov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"ljmd,d,cl,kbm->bjck", 2//1, [g_ooov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdle,c,dk,jel->bjck", 2//1, [g_vvov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,c,ek,ldj->bjck", 2//1, [g_vvov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,d,ej,lck->bjck", 2//1, [g_vvov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,e,cl,kdj->bjck", 2//1, [g_vvov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,b,cl,kdm->bjck", -2//1, [g_ooov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,b,dl,mck->bjck", -2//1, [g_ooov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,c,dk,mbl->bjck", -2//1, [g_ooov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,d,bm,lck->bjck", -2//1, [g_ooov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,d,cm,kbl->bjck", -2//1, [g_ooov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,c,jl,dek->bjck", -2//1, [g_vvov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"bdle,d,kl,cej->bjck", -2//1, [g_vvov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"ljmd,b,km,cdl->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"ljmd,c,lm,bdk->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"ljmd,d,kl,bcm->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"bdle,c,jl,dke->bjck", -2//1, [g_vvov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"bdle,d,kl,cje->bjck", -2//1, [g_vvov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"ljmd,b,km,cld->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"ljmd,c,lm,bkd->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"ljmd,d,kl,bmc->bjck", 2//1, [g_ooov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"bdle,e,kl,cdj->bjck", 2//1, [g_vvov, rxI_v, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"ljmd,b,kl,cdm->bjck", -2//1, [g_ooov, rxI_v, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"ljmd,c,kl,bdm->bjck", -2//1, [g_ooov, rxI_v, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"bdle,c,kl,dje->bjck", 2//1, [g_vvov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"bdle,d,jl,cke->bjck", 2//1, [g_vvov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"bdle,e,jl,ckd->bjck", 2//1, [g_vvov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"ljmd,b,lm,ckd->bjck", -2//1, [g_ooov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"ljmd,c,km,bld->bjck", -2//1, [g_ooov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"ljmd,d,km,blc->bjck", -2//1, [g_ooov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"bdle,c,je,ldk->bjck", -2//1, [g_vvov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdle,c,ld,jek->bjck", -2//1, [g_vvov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdle,d,ke,lcj->bjck", -2//1, [g_vvov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdle,d,lc,kej->bjck", -2//1, [g_vvov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdle,e,kd,jcl->bjck", -2//1, [g_vvov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ljmd,b,kd,mcl->bjck", 2//1, [g_ooov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ljmd,b,mc,kdl->bjck", 2//1, [g_ooov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ljmd,c,ld,mbk->bjck", 2//1, [g_ooov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ljmd,c,mb,ldk->bjck", 2//1, [g_ooov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"ljmd,d,lc,kbm->bjck", 2//1, [g_ooov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdle,c,kd,jel->bjck", 2//1, [g_vvov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bdle,c,ke,ldj->bjck", 2//1, [g_vvov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bdle,d,je,lck->bjck", 2//1, [g_vvov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bdle,e,lc,kdj->bjck", 2//1, [g_vvov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ljmd,b,lc,kdm->bjck", -2//1, [g_ooov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ljmd,b,ld,mck->bjck", -2//1, [g_ooov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ljmd,c,kd,mbl->bjck", -2//1, [g_ooov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ljmd,d,mb,lck->bjck", -2//1, [g_ooov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"ljmd,d,mc,kbl->bjck", -2//1, [g_ooov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bdle,c,kdl,ej->bjck", 2//1, [g_vvov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,c,kej,dl->bjck", 2//1, [g_vvov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,d,jcl,ek->bjck", 2//1, [g_vvov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,d,jek,cl->bjck", 2//1, [g_vvov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,e,lcj,dk->bjck", 2//1, [g_vvov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ljmd,b,lcm,dk->bjck", -2//1, [g_ooov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ljmd,b,ldk,cm->bjck", -2//1, [g_ooov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ljmd,c,kbm,dl->bjck", -2//1, [g_ooov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ljmd,c,kdl,bm->bjck", -2//1, [g_ooov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"ljmd,d,mbk,cl->bjck", -2//1, [g_ooov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdle,c,dj,kel->bjck", -2//1, [g_vvov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,c,el,kdj->bjck", -2//1, [g_vvov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdle,e,dj,lck->bjck", -2//1, [g_vvov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,b,dm,lck->bjck", 2//1, [g_ooov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,c,bl,kdm->bjck", 2//1, [g_ooov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,c,dm,kbl->bjck", 2//1, [g_ooov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ljmd,d,bl,mck->bjck", 2//1, [g_ooov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"dle,bj,ek,cdl->bjck", 4//1, [gAxxx_vov, r_vo, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"dle,bk,ej,cdl->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"dle,bl,ek,cdj->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"dle,ej,cl,bdk->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"dle,bj,cl,dke->bjck", 4//1, [gAxxx_vov, r_vo, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"dle,bk,cl,dje->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"dle,dj,cl,bke->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"dle,dj,ek,blc->bjck", -2//1, [gAxxx_vov, r_vo, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"dle,bj,dk,cel->bjck", -4//1, [gAxxx_vov, r_vo, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"dle,bk,dj,cel->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"dle,bl,dk,cej->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"dle,bj,dl,cke->bjck", -4//1, [gAxxx_vov, r_vo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,bk,dl,cje->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,bl,dj,cke->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,dj,bl,cke->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,ej,dk,blc->bjck", 2//1, [gAxxx_vov, r_vo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,bj,ke,cdl->bjck", 4//1, [gAxxx_vov, r_vo, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"dle,bk,je,cdl->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"dle,bl,ke,cdj->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"dle,ej,lc,bdk->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"dle,bj,lc,dke->bjck", 4//1, [gAxxx_vov, r_vo, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"dle,bk,lc,dje->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"dle,dj,ke,blc->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"dle,dj,lc,bke->bjck", -2//1, [gAxxx_vov, r_vo, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"dle,bj,kd,cel->bjck", -4//1, [gAxxx_vov, r_vo, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"dle,bk,jd,cel->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"dle,bl,kd,cej->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"dle,bj,ld,cke->bjck", -4//1, [gAxxx_vov, r_vo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dle,bk,ld,cje->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dle,bl,jd,cke->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dle,dj,lb,cke->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dle,ej,kd,blc->bjck", 2//1, [gAxxx_vov, r_vo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dle,bj,kdl,ce->bjck", 4//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bj,ldk,ce->bjck", 4//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bk,jdl,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bk,ldj,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bl,jdk,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bl,kdj,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,dj,kbl,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,dj,lbk,ce->bjck", -2//1, [gAxxx_vov, r_vo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dle,bj,cd,kel->bjck", -4//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,bj,de,lck->bjck", -4//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,bk,cd,jel->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,bk,de,lcj->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,bl,cd,kej->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,dj,be,lck->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,ej,bd,lck->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,ej,cd,kbl->bjck", 2//1, [gAxxx_vov, r_vo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dle,bj,dek,cl->bjck", -4//1, [gAxxx_vov, r_vo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"dle,bk,dej,cl->bjck", 2//1, [gAxxx_vov, r_vo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"dle,dj,bcl,ek->bjck", 2//1, [gAxxx_vov, r_vo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"dle,dj,bek,cl->bjck", 2//1, [gAxxx_vov, r_vo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"dle,bj,cld,ek->bjck", -4//1, [gAxxx_vov, r_vo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dle,bk,cld,ej->bjck", 2//1, [gAxxx_vov, r_vo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dle,bl,cjd,ek->bjck", 2//1, [gAxxx_vov, r_vo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dle,ej,bkd,cl->bjck", 2//1, [gAxxx_vov, r_vo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dle,bj,el,ckd->bjck", 4//1, [gAxxx_vov, r_vo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,bk,el,cjd->bjck", -2//1, [gAxxx_vov, r_vo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,bl,ej,ckd->bjck", -2//1, [gAxxx_vov, r_vo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,ej,bl,ckd->bjck", -2//1, [gAxxx_vov, r_vo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dle,,cjdl,bek->bjck", -2//1, [gAxxx_vov, rAI, t_vovo, txIxx_vvo])
    update_code!(func, ein"dle,,bjdl,cke->bjck", -8//1, [gAxxx_vov, rAI, t_vovo, txxxI_vov])
    update_code!(func, ein"dle,,bkdl,cje->bjck", 4//1, [gAxxx_vov, rAI, t_vovo, txxxI_vov])
    update_code!(func, ein"dle,,cldk,bje->bjck", 4//1, [gAxxx_vov, rAI, t_vovo, txxxI_vov])
    update_code!(func, ein"dle,,bjcl,dek->bjck", -4//1, [gAxxx_vov, rAI, t_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,,bkcl,dej->bjck", 2//1, [gAxxx_vov, rAI, t_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,,cldj,bek->bjck", 2//1, [gAxxx_vov, rAI, t_vovo, uxIxx_vvo])
    update_code!(func, ein"dle,,bcl,djek->bjck", 2//1, [gAxxx_vov, rAI, txIxx_vvo, u_vovo])
    update_code!(func, ein"dle,,bej,ckdl->bjck", 2//1, [gAxxx_vov, rAI, txIxx_vvo, u_vovo])
    update_code!(func, ein"dle,,cjel,bkd->bjck", -2//1, [gAxxx_vov, rAI, u_vovo, uxxxI_vov])
    update_code!(func, ein"dle,,ckel,bjd->bjck", 4//1, [gAxxx_vov, rAI, u_vovo, uxxxI_vov])
    update_code!(func, ein"dle,j,bkdl,ce->bjck", -2//1, [gAxxx_vov, rAx_o, t_vovo, txIxI_vv])
    update_code!(func, ein"dle,j,bldk,ce->bjck", -2//1, [gAxxx_vov, rAx_o, t_vovo, txIxI_vv])
    update_code!(func, ein"dle,j,cd,bkel->bjck", 2//1, [gAxxx_vov, rAx_o, txIxI_vv, u_vovo])
    update_code!(func, ein"dle,j,de,blck->bjck", 2//1, [gAxxx_vov, rAx_o, txIxI_vv, u_vovo])
    update_code!(func, ein"dle,l,bd,ckej->bjck", 2//1, [gAxxx_vov, rAx_o, txIxI_vv, u_vovo])
    update_code!(func, ein"dle,l,be,ckdj->bjck", 2//1, [gAxxx_vov, rAx_o, txIxI_vv, u_vovo])
    update_code!(func, ein"dle,j,bek,cdl->bjck", -2//1, [gAxxx_vov, rAx_o, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"dle,l,bdk,cej->bjck", -2//1, [gAxxx_vov, rAx_o, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"dle,j,bcl,dke->bjck", -2//1, [gAxxx_vov, rAx_o, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"dle,j,cdl,bke->bjck", -2//1, [gAxxx_vov, rAx_o, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"dle,l,bej,ckd->bjck", 4//1, [gAxxx_vov, rAx_o, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"dle,l,bek,cjd->bjck", -2//1, [gAxxx_vov, rAx_o, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"dle,j,bdk,cel->bjck", 2//1, [gAxxx_vov, rAx_o, txIxx_vvo, uxIxx_vvo])
    update_code!(func, ein"dle,j,dek,bcl->bjck", 2//1, [gAxxx_vov, rAx_o, txIxx_vvo, uxIxx_vvo])
    update_code!(func, ein"dle,j,bdl,cke->bjck", 2//1, [gAxxx_vov, rAx_o, txIxx_vvo, uxxxI_vov])
    update_code!(func, ein"dle,l,bdj,cke->bjck", 2//1, [gAxxx_vov, rAx_o, txIxx_vvo, uxxxI_vov])
    update_code!(func, ein"dle,j,blc,dke->bjck", -2//1, [gAxxx_vov, rAx_o, txxxI_vov, txxxI_vov])
    update_code!(func, ein"dle,l,bjd,cke->bjck", -8//1, [gAxxx_vov, rAx_o, txxxI_vov, txxxI_vov])
    update_code!(func, ein"dle,j,bkd,cel->bjck", 2//1, [gAxxx_vov, rAx_o, txxxI_vov, uxIxx_vvo])
    update_code!(func, ein"dle,j,cld,bek->bjck", 2//1, [gAxxx_vov, rAx_o, txxxI_vov, uxIxx_vvo])
    update_code!(func, ein"dle,j,bld,cke->bjck", 2//1, [gAxxx_vov, rAx_o, txxxI_vov, uxxxI_vov])
    update_code!(func, ein"dle,l,cje,bkd->bjck", 2//1, [gAxxx_vov, rAx_o, txxxI_vov, uxxxI_vov])
    update_code!(func, ein"dle,j,bel,ckd->bjck", -2//1, [gAxxx_vov, rAx_o, uxIxx_vvo, uxxxI_vov])
    update_code!(func, ein"dle,b,cjdl,ek->bjck", -2//1, [gAxxx_vov, rxI_v, t_vovo, tAIxx_vo])
    update_code!(func, ein"dle,b,dkej,cl->bjck", -2//1, [gAxxx_vov, rxI_v, t_vovo, tAIxx_vo])
    update_code!(func, ein"dle,b,cjdl,ke->bjck", -2//1, [gAxxx_vov, rxI_v, t_vovo, tAxxI_ov])
    update_code!(func, ein"dle,b,dkej,lc->bjck", -2//1, [gAxxx_vov, rxI_v, t_vovo, tAxxI_ov])
    update_code!(func, ein"dle,b,cldj,ek->bjck", 2//1, [gAxxx_vov, rxI_v, t_vovo, uAIxx_vo])
    update_code!(func, ein"dle,b,djek,cl->bjck", 2//1, [gAxxx_vov, rxI_v, t_vovo, uAIxx_vo])
    update_code!(func, ein"dle,b,dk,cjel->bjck", 2//1, [gAxxx_vov, rxI_v, tAIxx_vo, u_vovo])
    update_code!(func, ein"dle,b,dl,ckej->bjck", 2//1, [gAxxx_vov, rxI_v, tAIxx_vo, u_vovo])
    update_code!(func, ein"dle,e,bl,ckdj->bjck", 2//1, [gAxxx_vov, rxI_v, tAIxx_vo, u_vovo])
    update_code!(func, ein"dle,e,dj,blck->bjck", 2//1, [gAxxx_vov, rxI_v, tAIxx_vo, u_vovo])
    update_code!(func, ein"dle,b,kd,cjel->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxI_ov, u_vovo])
    update_code!(func, ein"dle,b,ld,ckej->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxI_ov, u_vovo])
    update_code!(func, ein"dle,e,jd,blck->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxI_ov, u_vovo])
    update_code!(func, ein"dle,e,lb,ckdj->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxI_ov, u_vovo])
    update_code!(func, ein"dle,b,jek,cdl->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,b,kdl,cej->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,b,kej,cdl->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,b,ldk,cej->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,e,jcl,bdk->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,e,jdk,bcl->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dle,b,jcl,dke->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,b,kdl,cje->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,b,lcj,dke->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,b,ldk,cje->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,e,jcl,bkd->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,e,jdk,blc->bjck", -2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dle,b,jdk,cel->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"dle,b,kdj,cel->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"dle,d,jcl,bek->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"dle,d,jek,bcl->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"dle,b,jdl,cke->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,b,ldj,cke->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,d,lbk,cje->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,e,lbk,cjd->bjck", 2//1, [gAxxx_vov, rxI_v, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,b,cdj,kel->bjck", 2//1, [gAxxx_vov, rxI_v, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"dle,b,dej,lck->bjck", 2//1, [gAxxx_vov, rxI_v, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"dle,b,dek,jcl->bjck", 2//1, [gAxxx_vov, rxI_v, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"dle,b,cjd,kel->bjck", 2//1, [gAxxx_vov, rxI_v, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dle,b,cld,jek->bjck", 2//1, [gAxxx_vov, rxI_v, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dle,b,dje,lck->bjck", 2//1, [gAxxx_vov, rxI_v, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dle,b,ckdj,el->bjck", -2//1, [gAxxx_vov, rxI_v, u_vovo, uAIxx_vo])
    update_code!(func, ein"dle,d,blck,ej->bjck", -2//1, [gAxxx_vov, rxI_v, u_vovo, uAIxx_vo])
    update_code!(func, ein"dle,d,ckej,bl->bjck", -2//1, [gAxxx_vov, rxI_v, u_vovo, uAIxx_vo])
    update_code!(func, ein"dle,b,jel,ckd->bjck", -2//1, [gAxxx_vov, rxI_v, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,d,lbj,cke->bjck", -2//1, [gAxxx_vov, rxI_v, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dle,e,lbj,ckd->bjck", -2//1, [gAxxx_vov, rxI_v, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,bj,cm,kdl->bjck", -4//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bj,dk,mcl->bjck", -4//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bk,cm,jdl->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bk,dj,mcl->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bl,cm,kdj->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bl,dk,mcj->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bm,dk,jcl->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,dj,cm,kbl->bjck", 2//1, [gxIxx_oov, r_vo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmd,bj,cl,kdm->bjck", 4//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bj,dl,mck->bjck", 4//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bk,cl,jdm->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bk,dl,mcj->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bl,dj,mck->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bm,cl,kdj->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,dj,bl,mck->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,dj,cl,kbm->bjck", -2//1, [gxIxx_oov, r_vo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bj,km,cdl->bjck", -4//1, [gxIxx_oov, r_vo, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"lmd,bk,jm,cdl->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"lmd,bl,km,cdj->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"lmd,dj,km,bcl->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"lmd,bj,km,cld->bjck", -4//1, [gxIxx_oov, r_vo, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"lmd,bk,jm,cld->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"lmd,bl,km,cjd->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"lmd,dj,km,blc->bjck", 2//1, [gxIxx_oov, r_vo, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"lmd,bj,kl,cdm->bjck", 4//1, [gxIxx_oov, r_vo, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"lmd,bk,jl,cdm->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"lmd,bm,kl,cdj->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"lmd,bj,lm,ckd->bjck", 4//1, [gxIxx_oov, r_vo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmd,bk,lm,cjd->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmd,bl,jm,ckd->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmd,bm,jl,ckd->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmd,dj,kl,bmc->bjck", -2//1, [gxIxx_oov, r_vo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmd,bj,kd,mcl->bjck", -4//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bj,mc,kdl->bjck", -4//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bk,jd,mcl->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bk,mc,jdl->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bl,kd,mcj->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bl,mc,kdj->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bm,kd,jcl->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,dj,mc,kbl->bjck", 2//1, [gxIxx_oov, r_vo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmd,bj,lc,kdm->bjck", 4//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bj,ld,mck->bjck", 4//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bk,lc,jdm->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bk,ld,mcj->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bl,jd,mck->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bm,lc,kdj->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,dj,lb,mck->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,dj,lc,kbm->bjck", -2//1, [gxIxx_oov, r_vo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmd,bj,lcm,dk->bjck", 4//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bj,ldk,cm->bjck", 4//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bk,lcm,dj->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bk,ldj,cm->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bl,jcm,dk->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bl,jdk,cm->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bm,lcj,dk->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,dj,lbk,cm->bjck", -2//1, [gxIxx_oov, r_vo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmd,bj,dm,lck->bjck", -4//1, [gxIxx_oov, r_vo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bk,dm,lcj->bjck", 2//1, [gxIxx_oov, r_vo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,bm,dj,lck->bjck", 2//1, [gxIxx_oov, r_vo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,dj,bm,lck->bjck", 2//1, [gxIxx_oov, r_vo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmd,,jcl,bkdm->bjck", -2//1, [gxIxx_oov, rAI, tAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,,jcm,bldk->bjck", -2//1, [gxIxx_oov, rAI, tAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,,jdk,blcm->bjck", -2//1, [gxIxx_oov, rAI, tAxxx_ovo, u_vovo])
    update_code!(func, ein"lmd,,blck,jdm->bjck", 2//1, [gxIxx_oov, rAI, u_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,,bmck,ldj->bjck", 2//1, [gxIxx_oov, rAI, u_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,,ckdj,lbm->bjck", 2//1, [gxIxx_oov, rAI, u_vovo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bkdl,cm->bjck", 2//1, [gxIxx_oov, rAx_o, t_vovo, tAIxx_vo])
    update_code!(func, ein"lmd,j,bmcl,dk->bjck", 2//1, [gxIxx_oov, rAx_o, t_vovo, tAIxx_vo])
    update_code!(func, ein"lmd,j,bkdl,mc->bjck", 2//1, [gxIxx_oov, rAx_o, t_vovo, tAxxI_ov])
    update_code!(func, ein"lmd,j,bmcl,kd->bjck", 2//1, [gxIxx_oov, rAx_o, t_vovo, tAxxI_ov])
    update_code!(func, ein"lmd,j,blcm,dk->bjck", -2//1, [gxIxx_oov, rAx_o, t_vovo, uAIxx_vo])
    update_code!(func, ein"lmd,j,bldk,cm->bjck", -2//1, [gxIxx_oov, rAx_o, t_vovo, uAIxx_vo])
    update_code!(func, ein"lmd,j,cl,bkdm->bjck", -2//1, [gxIxx_oov, rAx_o, tAIxx_vo, u_vovo])
    update_code!(func, ein"lmd,j,dl,bmck->bjck", -2//1, [gxIxx_oov, rAx_o, tAIxx_vo, u_vovo])
    update_code!(func, ein"lmd,m,bl,ckdj->bjck", -2//1, [gxIxx_oov, rAx_o, tAIxx_vo, u_vovo])
    update_code!(func, ein"lmd,m,dj,blck->bjck", -2//1, [gxIxx_oov, rAx_o, tAIxx_vo, u_vovo])
    update_code!(func, ein"lmd,j,lc,bkdm->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,j,ld,bmck->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,m,jd,blck->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,m,lb,ckdj->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxI_ov, u_vovo])
    update_code!(func, ein"lmd,j,kbm,cdl->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"lmd,j,mbk,cdl->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"lmd,m,jcl,bdk->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"lmd,m,jdk,bcl->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"lmd,j,kbm,cld->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,kdl,bmc->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,lcm,bkd->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,ldk,bmc->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,mbk,cld->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,mcl,bkd->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,m,jcl,bkd->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,m,jdk,blc->bjck", 2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"lmd,j,kbl,cdm->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"lmd,j,lbk,cdm->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"lmd,l,jcm,bdk->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"lmd,l,jdk,bcm->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"lmd,j,lbm,ckd->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,j,mbl,ckd->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,l,mbk,cjd->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,m,lbk,cjd->bjck", -2//1, [gxIxx_oov, rAx_o, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,j,bcl,kdm->bjck", -2//1, [gxIxx_oov, rAx_o, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bcm,ldk->bjck", -2//1, [gxIxx_oov, rAx_o, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bdk,lcm->bjck", -2//1, [gxIxx_oov, rAx_o, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bdl,mck->bjck", -2//1, [gxIxx_oov, rAx_o, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"lmd,j,blc,kdm->bjck", -2//1, [gxIxx_oov, rAx_o, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"lmd,j,bld,mck->bjck", -2//1, [gxIxx_oov, rAx_o, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"lmd,j,blck,dm->bjck", 2//1, [gxIxx_oov, rAx_o, u_vovo, uAIxx_vo])
    update_code!(func, ein"lmd,l,bmck,dj->bjck", 2//1, [gxIxx_oov, rAx_o, u_vovo, uAIxx_vo])
    update_code!(func, ein"lmd,l,ckdj,bm->bjck", 2//1, [gxIxx_oov, rAx_o, u_vovo, uAIxx_vo])
    update_code!(func, ein"lmd,j,lck,bdm->bjck", 2//1, [gxIxx_oov, rAx_o, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"lmd,l,mbj,ckd->bjck", 2//1, [gxIxx_oov, rAx_o, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,m,lbj,ckd->bjck", 2//1, [gxIxx_oov, rAx_o, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"lmd,b,cjdl,km->bjck", 2//1, [gxIxx_oov, rxI_v, t_vovo, tAxAx_oo])
    update_code!(func, ein"lmd,b,cldj,km->bjck", 2//1, [gxIxx_oov, rxI_v, t_vovo, tAxAx_oo])
    update_code!(func, ein"lmd,b,kl,cjdm->bjck", -2//1, [gxIxx_oov, rxI_v, tAxAx_oo, u_vovo])
    update_code!(func, ein"lmd,b,lm,ckdj->bjck", -2//1, [gxIxx_oov, rxI_v, tAxAx_oo, u_vovo])
    update_code!(func, ein"lmd,d,jl,bmck->bjck", -2//1, [gxIxx_oov, rxI_v, tAxAx_oo, u_vovo])
    update_code!(func, ein"lmd,d,jm,blck->bjck", -2//1, [gxIxx_oov, rxI_v, tAxAx_oo, u_vovo])
    update_code!(func, ein"lmd,b,jcm,kdl->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,b,jdk,mcl->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,b,kdj,mcl->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,b,kdl,mcj->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,d,jbm,lck->bjck", -4//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,d,jcl,kbm->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,d,jcl,mbk->bjck", 2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,d,lbj,mck->bjck", 8//1, [gxIxx_oov, rxI_v, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lmd,b,jcl,kdm->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,jdl,mck->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,lcj,kdm->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,lcm,jdk->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,ldj,mck->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,ldk,jcm->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,d,jbl,mck->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,d,lbk,mcj->bjck", -2//1, [gxIxx_oov, rxI_v, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lmd,b,jdm,lck->bjck", 2//1, [gxIxx_oov, rxI_v, uAxxx_ovo, uAxxx_ovo])
    finalize_eT_function(func, "mu_4_H_nu_1_s", "doublet_ccsd")
end

println(io, s)
end
