include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("mu_4_H_1_nu_2_ss.F90", "w") do io
s = let
    func = FortranFunction(("rho_aibj", ["v", "o", "v", "o"]))
    FAx_v = ("FAx_v", true)
    r_vovo = ("r_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    tAIxI_v = ("tAIxI_v", true)
    FxI_o = ("FxI_o", true)
    tAIAx_o = ("tAIAx_o", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    rAIAI = ("rAIAI", true)
    u_vovo = ("u_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    rAxAx_oo = ("rAxAx_oo", true)
    txIxI_vv = ("txIxI_vv", true)
    rxIxI_vv = ("rxIxI_vv", true)
    tAxAx_oo = ("tAxAx_oo", true)
    gAIxx_ov = ("gAIxx_ov", true)
    uAIxx_vo = ("uAIxx_vo", true)
    gAxAx_vv = ("gAxAx_vv", true)
    t_vovo = ("t_aibj", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAxxI_vo = ("gAxxI_vo", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    gxIxI_oo = ("gxIxI_oo", true)
    update_code!(func, ein"d,bjck,d->bjck", 8//1, [FAx_v, r_vovo, tAIxI_v])
    update_code!(func, ein"d,bkcj,d->bjck", -4//1, [FAx_v, r_vovo, tAIxI_v])
    update_code!(func, ein"l,bjck,l->bjck", -8//1, [FxI_o, r_vovo, tAIAx_o])
    update_code!(func, ein"l,bkcj,l->bjck", 4//1, [FxI_o, r_vovo, tAIAx_o])
    update_code!(func, ein"bdce,,djek->bjck", 2//1, [g_vvvv, rAIAI, u_vovo])
    update_code!(func, ein"ljmk,,blcm->bjck", 2//1, [g_oooo, rAIAI, u_vovo])
    update_code!(func, ein"bdce,jk,de->bjck", 2//1, [g_vvvv, rAxAx_oo, txIxI_vv])
    update_code!(func, ein"ljmk,bc,lm->bjck", 2//1, [g_oooo, rxIxI_vv, tAxAx_oo])
    update_code!(func, ein"ld,bjck,dl->bjck", 8//1, [gAIxx_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"ld,bkcj,dl->bjck", -4//1, [gAIxx_ov, r_vovo, uAIxx_vo])
    update_code!(func, ein"de,bjck,de->bjck", 4//1, [gAxAx_vv, r_vovo, txIxI_vv])
    update_code!(func, ein"de,bkcj,de->bjck", -2//1, [gAxAx_vv, r_vovo, txIxI_vv])
    update_code!(func, ein"de,bc,djek->bjck", 2//1, [gAxAx_vv, rxIxI_vv, t_vovo])
    update_code!(func, ein"dl,bjck,dl->bjck", -8//1, [gAxxI_vo, r_vovo, tAIxx_vo])
    update_code!(func, ein"dl,bkcj,dl->bjck", 4//1, [gAxxI_vo, r_vovo, tAIxx_vo])
    update_code!(func, ein"dl,bjck,ld->bjck", -8//1, [gAxxI_vo, r_vovo, tAxxI_ov])
    update_code!(func, ein"dl,bkcj,ld->bjck", 4//1, [gAxxI_vo, r_vovo, tAxxI_ov])
    update_code!(func, ein"lm,bjck,lm->bjck", 4//1, [gxIxI_oo, r_vovo, tAxAx_oo])
    update_code!(func, ein"lm,bkcj,lm->bjck", -2//1, [gxIxI_oo, r_vovo, tAxAx_oo])
    update_code!(func, ein"lm,jk,blcm->bjck", 2//1, [gxIxI_oo, rAxAx_oo, t_vovo])
    finalize_eT_function(func, "mu_4_H_1_nu_2_ss", "doublet_ccsd")
end

println(io, s)
end
