include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("omega_mu2_3_1_s.F90", "w") do io
s = let
    func = FortranFunction(("omega_aibj", ["v", "o", "v", "o"]))
    LAxxx_vvo = ("LAxxx_vvo", true)
    txIxI_vv = ("txIxI_vv", true)
    xAx_o = ("xAx_o", true)
    LxxxI_voo = ("LxxxI_voo", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    g_vovv = ("g_vovv", true)
    tAIxI_v = ("tAIxI_v", true)
    gAIxI_o = ("gAIxI_o", true)
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAIxx_vv = ("gAIxx_vv", true)
    uxIxx_vvo = ("uxIxx_vvo", true)
    uxxxI_vov = ("uxxxI_vov", true)
    gAIxx_oo = ("gAIxx_oo", true)
    gAxxI_oo = ("gAxxI_oo", true)
    txIxx_vvo = ("txIxx_vvo", true)
    gAxxI_vv = ("gAxxI_vv", true)
    txxxI_vov = ("txxxI_vov", true)
    gAxxx_ovv = ("gAxxx_ovv", true)
    gAxxx_vvo = ("gAxxx_vvo", true)
    gxIxI_vo = ("gxIxI_vo", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    gxIxx_vvv = ("gxIxx_vvv", true)
    uAIxx_vo = ("uAIxx_vo", true)
    gxIxx_voo = ("gxIxx_voo", true)
    gxxxI_voo = ("gxxxI_voo", true)
    F_ov = ("wf%fock_ia", false)
    L_vvov = ("L_vvov", true)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAxxx_vov = ("LAxxx_vov", true)
    LxIxx_oov = ("LxIxx_oov", true)
    g_vvov = ("g_vvov", true)
    g_ooov = ("g_ooov", true)
    gAxxx_vov = ("gAxxx_vov", true)
    gxIxx_oov = ("gxIxx_oov", true)
    update_code!(func, ein"dbj,cd,k->bjck", 1//1, [LAxxx_vvo, txIxI_vv, xAx_o])
    update_code!(func, ein"bjl,cl,k->bjck", -1//1, [LxxxI_voo, tAIxx_vo, xAx_o])
    update_code!(func, ein"bjl,lc,k->bjck", -1//1, [LxxxI_voo, tAxxI_ov, xAx_o])
    update_code!(func, ein"bjcd,d,k->bjck", 2//1, [g_vovv, tAIxI_v, xAx_o])
    update_code!(func, ein"bkcd,d,j->bjck", -1//1, [g_vovv, tAIxI_v, xAx_o])
    update_code!(func, ein"l,bjcl,k->bjck", -2//1, [gAIxI_o, t_vovo, xAx_o])
    update_code!(func, ein"l,bkcl,j->bjck", 1//1, [gAIxI_o, t_vovo, xAx_o])
    update_code!(func, ein"bd,cdj,k->bjck", 1//1, [gAIxx_vv, uxIxx_vvo, xAx_o])
    update_code!(func, ein"bd,ckd,j->bjck", 1//1, [gAIxx_vv, uxxxI_vov, xAx_o])
    update_code!(func, ein"lj,blc,k->bjck", -1//1, [gAIxx_oo, uxxxI_vov, xAx_o])
    update_code!(func, ein"jl,bcl,k->bjck", 1//1, [gAxxI_oo, txIxx_vvo, xAx_o])
    update_code!(func, ein"db,cdj,k->bjck", -1//1, [gAxxI_vv, txIxx_vvo, xAx_o])
    update_code!(func, ein"jl,blc,k->bjck", 1//1, [gAxxI_oo, txxxI_vov, xAx_o])
    update_code!(func, ein"db,cjd,k->bjck", -1//1, [gAxxI_vv, txxxI_vov, xAx_o])
    update_code!(func, ein"db,ckd,j->bjck", 1//1, [gAxxI_vv, uxxxI_vov, xAx_o])
    update_code!(func, ein"jcd,bd,k->bjck", -1//1, [gAxxx_ovv, txIxI_vv, xAx_o])
    update_code!(func, ein"dbk,cd,j->bjck", -1//1, [gAxxx_vvo, txIxI_vv, xAx_o])
    update_code!(func, ein"bl,jcl,k->bjck", 1//1, [gxIxI_vo, tAxxx_ovo, xAx_o])
    update_code!(func, ein"bl,lcj,k->bjck", 1//1, [gxIxI_vo, tAxxx_ovo, xAx_o])
    update_code!(func, ein"bl,lck,j->bjck", -1//1, [gxIxI_vo, uAxxx_ovo, xAx_o])
    update_code!(func, ein"bcd,dj,k->bjck", -1//1, [gxIxx_vvv, tAIxx_vo, xAx_o])
    update_code!(func, ein"bcd,jd,k->bjck", -1//1, [gxIxx_vvv, tAxxI_ov, xAx_o])
    update_code!(func, ein"bcd,dk,j->bjck", 1//1, [gxIxx_vvv, uAIxx_vo, xAx_o])
    update_code!(func, ein"blk,cl,j->bjck", -1//1, [gxIxx_voo, uAIxx_vo, xAx_o])
    update_code!(func, ein"bkl,cl,j->bjck", 1//1, [gxxxI_voo, tAIxx_vo, xAx_o])
    update_code!(func, ein"bkl,lc,j->bjck", 1//1, [gxxxI_voo, tAxxI_ov, xAx_o])
    update_code!(func, ein"ld,bjcl,d,k->bjck", -2//1, [F_ov, t_vovo, tAIxI_v, xAx_o])
    update_code!(func, ein"ld,bkcl,d,j->bjck", 1//1, [F_ov, t_vovo, tAIxI_v, xAx_o])
    update_code!(func, ein"ld,dj,bcl,k->bjck", 1//1, [F_ov, tAIxx_vo, txIxx_vvo, xAx_o])
    update_code!(func, ein"ld,bl,cjd,k->bjck", 1//1, [F_ov, tAIxx_vo, txxxI_vov, xAx_o])
    update_code!(func, ein"ld,bl,ckd,j->bjck", -1//1, [F_ov, tAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"ld,jd,bcl,k->bjck", 1//1, [F_ov, tAxxI_ov, txIxx_vvo, xAx_o])
    update_code!(func, ein"ld,lb,cjd,k->bjck", 1//1, [F_ov, tAxxI_ov, txxxI_vov, xAx_o])
    update_code!(func, ein"ld,lb,ckd,j->bjck", -1//1, [F_ov, tAxxI_ov, uxxxI_vov, xAx_o])
    update_code!(func, ein"ld,jcl,bd,k->bjck", 1//1, [F_ov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"ld,lbk,cd,j->bjck", 1//1, [F_ov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"ld,cd,lbj,k->bjck", -1//1, [F_ov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"ld,cdj,bl,k->bjck", -1//1, [F_ov, txIxx_vvo, uAIxx_vo, xAx_o])
    update_code!(func, ein"ld,blc,dj,k->bjck", -1//1, [F_ov, txxxI_vov, uAIxx_vo, xAx_o])
    update_code!(func, ein"bdle,d,ckel,j->bjck", 1//1, [L_vvov, tAIxI_v, u_vovo, xAx_o])
    update_code!(func, ein"dle,bd,ckel,j->bjck", 1//1, [LAxxx_vov, txIxI_vv, u_vovo, xAx_o])
    update_code!(func, ein"dle,bel,cjd,k->bjck", -1//1, [LAxxx_vov, txIxx_vvo, txxxI_vov, xAx_o])
    update_code!(func, ein"lmd,bl,ckdm,j->bjck", -1//1, [LxIxx_oov, tAIxx_vo, u_vovo, xAx_o])
    update_code!(func, ein"lmd,lb,ckdm,j->bjck", -1//1, [LxIxx_oov, tAxxI_ov, u_vovo, xAx_o])
    update_code!(func, ein"bdle,d,cjel,k->bjck", -1//1, [g_vvov, tAIxI_v, u_vovo, xAx_o])
    update_code!(func, ein"bdle,e,cldj,k->bjck", -1//1, [g_vvov, tAIxI_v, u_vovo, xAx_o])
    update_code!(func, ein"ljmd,d,blcm,k->bjck", 1//1, [g_ooov, tAIxI_v, u_vovo, xAx_o])
    update_code!(func, ein"bdle,ek,cdl,j->bjck", 1//1, [g_vvov, tAIxx_vo, txIxx_vvo, xAx_o])
    update_code!(func, ein"ljmd,dl,bcm,k->bjck", -1//1, [g_ooov, tAIxx_vo, txIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,cl,dke,j->bjck", 1//1, [g_vvov, tAIxx_vo, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,dl,cje,k->bjck", 1//1, [g_vvov, tAIxx_vo, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,ej,cld,k->bjck", 1//1, [g_vvov, tAIxx_vo, txxxI_vov, xAx_o])
    update_code!(func, ein"ljmd,bm,cld,k->bjck", -1//1, [g_ooov, tAIxx_vo, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,dk,cel,j->bjck", -1//1, [g_vvov, tAIxx_vo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"ljmd,cl,bdm,k->bjck", 1//1, [g_ooov, tAIxx_vo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,cl,dje,k->bjck", -1//1, [g_vvov, tAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"bdle,dl,cke,j->bjck", -1//1, [g_vvov, tAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"ljmd,cm,bld,k->bjck", 1//1, [g_ooov, tAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"bdle,ke,cdl,j->bjck", 1//1, [g_vvov, tAxxI_ov, txIxx_vvo, xAx_o])
    update_code!(func, ein"ljmd,ld,bcm,k->bjck", -1//1, [g_ooov, tAxxI_ov, txIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,je,cld,k->bjck", 1//1, [g_vvov, tAxxI_ov, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,lc,dke,j->bjck", 1//1, [g_vvov, tAxxI_ov, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,ld,cje,k->bjck", 1//1, [g_vvov, tAxxI_ov, txxxI_vov, xAx_o])
    update_code!(func, ein"ljmd,mb,cld,k->bjck", -1//1, [g_ooov, tAxxI_ov, txxxI_vov, xAx_o])
    update_code!(func, ein"bdle,kd,cel,j->bjck", -1//1, [g_vvov, tAxxI_ov, uxIxx_vvo, xAx_o])
    update_code!(func, ein"ljmd,lc,bdm,k->bjck", 1//1, [g_ooov, tAxxI_ov, uxIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,lc,dje,k->bjck", -1//1, [g_vvov, tAxxI_ov, uxxxI_vov, xAx_o])
    update_code!(func, ein"bdle,ld,cke,j->bjck", -1//1, [g_vvov, tAxxI_ov, uxxxI_vov, xAx_o])
    update_code!(func, ein"ljmd,mc,bld,k->bjck", 1//1, [g_ooov, tAxxI_ov, uxxxI_vov, xAx_o])
    update_code!(func, ein"bdle,jcl,de,k->bjck", 1//1, [g_vvov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"bdle,kdl,ce,j->bjck", 1//1, [g_vvov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"bdle,lcj,de,k->bjck", 1//1, [g_vvov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"bdle,ldk,ce,j->bjck", 1//1, [g_vvov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"ljmd,lcm,bd,k->bjck", -1//1, [g_ooov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"ljmd,mcl,bd,k->bjck", -1//1, [g_ooov, tAxxx_ovo, txIxI_vv, xAx_o])
    update_code!(func, ein"bdle,cd,jel,k->bjck", -1//1, [g_vvov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"bdle,cd,kel,j->bjck", -1//1, [g_vvov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"bdle,ce,ldj,k->bjck", -1//1, [g_vvov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"bdle,de,lck,j->bjck", -1//1, [g_vvov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"ljmd,cd,mbl,k->bjck", 1//1, [g_ooov, txIxI_vv, uAxxx_ovo, xAx_o])
    update_code!(func, ein"bdle,cdl,ej,k->bjck", -1//1, [g_vvov, txIxx_vvo, uAIxx_vo, xAx_o])
    update_code!(func, ein"bdle,cej,dl,k->bjck", -1//1, [g_vvov, txIxx_vvo, uAIxx_vo, xAx_o])
    update_code!(func, ein"bdle,dek,cl,j->bjck", -1//1, [g_vvov, txIxx_vvo, uAIxx_vo, xAx_o])
    update_code!(func, ein"ljmd,cdl,bm,k->bjck", 1//1, [g_ooov, txIxx_vvo, uAIxx_vo, xAx_o])
    update_code!(func, ein"bdle,cld,ek,j->bjck", -1//1, [g_vvov, txxxI_vov, uAIxx_vo, xAx_o])
    update_code!(func, ein"ljmd,bmc,dl,k->bjck", 1//1, [g_ooov, txxxI_vov, uAIxx_vo, xAx_o])
    update_code!(func, ein"bdle,dj,cel,k->bjck", 1//1, [g_vvov, uAIxx_vo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,el,cdj,k->bjck", 1//1, [g_vvov, uAIxx_vo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"ljmd,bl,cdm,k->bjck", -1//1, [g_ooov, uAIxx_vo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"bdle,el,ckd,j->bjck", 1//1, [g_vvov, uAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"ljmd,dm,blc,k->bjck", -1//1, [g_ooov, uAIxx_vo, uxxxI_vov, xAx_o])
    update_code!(func, ein"dle,bjcl,de,k->bjck", -2//1, [gAxxx_vov, t_vovo, txIxI_vv, xAx_o])
    update_code!(func, ein"dle,bkcl,de,j->bjck", 1//1, [gAxxx_vov, t_vovo, txIxI_vv, xAx_o])
    update_code!(func, ein"dle,cjdl,be,k->bjck", 1//1, [gAxxx_vov, t_vovo, txIxI_vv, xAx_o])
    update_code!(func, ein"dle,cldj,be,k->bjck", 1//1, [gAxxx_vov, t_vovo, txIxI_vv, xAx_o])
    update_code!(func, ein"dle,bd,cjel,k->bjck", -1//1, [gAxxx_vov, txIxI_vv, u_vovo, xAx_o])
    update_code!(func, ein"dle,bcl,dej,k->bjck", 1//1, [gAxxx_vov, txIxx_vvo, txIxx_vvo, xAx_o])
    update_code!(func, ein"dle,bdl,cej,k->bjck", 1//1, [gAxxx_vov, txIxx_vvo, txIxx_vvo, xAx_o])
    update_code!(func, ein"dle,bcl,dje,k->bjck", 1//1, [gAxxx_vov, txIxx_vvo, txxxI_vov, xAx_o])
    update_code!(func, ein"dle,bel,ckd,j->bjck", 4//1, [gAxxx_vov, txIxx_vvo, txxxI_vov, xAx_o])
    update_code!(func, ein"dle,bcl,dek,j->bjck", -1//1, [gAxxx_vov, txIxx_vvo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"dle,bdj,cel,k->bjck", -1//1, [gAxxx_vov, txIxx_vvo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"dle,bdk,cel,j->bjck", -1//1, [gAxxx_vov, txIxx_vvo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"dle,bdl,cke,j->bjck", -1//1, [gAxxx_vov, txIxx_vvo, uxxxI_vov, xAx_o])
    update_code!(func, ein"dle,bjd,cle,k->bjck", -2//1, [gAxxx_vov, txxxI_vov, txxxI_vov, xAx_o])
    update_code!(func, ein"dle,bkd,cle,j->bjck", 1//1, [gAxxx_vov, txxxI_vov, txxxI_vov, xAx_o])
    update_code!(func, ein"dle,cld,bek,j->bjck", -1//1, [gAxxx_vov, txxxI_vov, uxIxx_vvo, xAx_o])
    update_code!(func, ein"dle,cld,bje,k->bjck", -1//1, [gAxxx_vov, txxxI_vov, uxxxI_vov, xAx_o])
    update_code!(func, ein"lmd,bjcm,dl,k->bjck", 2//1, [gxIxx_oov, t_vovo, tAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,bkcm,dl,j->bjck", -1//1, [gxIxx_oov, t_vovo, tAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,blcm,dj,k->bjck", -1//1, [gxIxx_oov, t_vovo, tAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,cjdl,bm,k->bjck", -1//1, [gxIxx_oov, t_vovo, tAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,bjcm,ld,k->bjck", 2//1, [gxIxx_oov, t_vovo, tAxxI_ov, xAx_o])
    update_code!(func, ein"lmd,bkcm,ld,j->bjck", -1//1, [gxIxx_oov, t_vovo, tAxxI_ov, xAx_o])
    update_code!(func, ein"lmd,blcm,jd,k->bjck", -1//1, [gxIxx_oov, t_vovo, tAxxI_ov, xAx_o])
    update_code!(func, ein"lmd,cjdl,mb,k->bjck", -1//1, [gxIxx_oov, t_vovo, tAxxI_ov, xAx_o])
    update_code!(func, ein"lmd,bjcl,dm,k->bjck", -2//1, [gxIxx_oov, t_vovo, uAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,bkcl,dm,j->bjck", 1//1, [gxIxx_oov, t_vovo, uAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,bmcl,dj,k->bjck", 1//1, [gxIxx_oov, t_vovo, uAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,cldj,bm,k->bjck", 1//1, [gxIxx_oov, t_vovo, uAIxx_vo, xAx_o])
    update_code!(func, ein"lmd,bl,cjdm,k->bjck", 1//1, [gxIxx_oov, tAIxx_vo, u_vovo, xAx_o])
    update_code!(func, ein"lmd,lb,cjdm,k->bjck", 1//1, [gxIxx_oov, tAxxI_ov, u_vovo, xAx_o])
    update_code!(func, ein"lmd,jcm,bdl,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,jdl,bcm,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,ldj,bcm,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,mbk,cdl,j->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,jcm,bld,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txxxI_vov, xAx_o])
    update_code!(func, ein"lmd,lbm,cjd,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txxxI_vov, xAx_o])
    update_code!(func, ein"lmd,mbk,cld,j->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txxxI_vov, xAx_o])
    update_code!(func, ein"lmd,mbl,cjd,k->bjck", -1//1, [gxIxx_oov, tAxxx_ovo, txxxI_vov, xAx_o])
    update_code!(func, ein"lmd,jcl,bdm,k->bjck", 1//1, [gxIxx_oov, tAxxx_ovo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,lbk,cdm,j->bjck", 1//1, [gxIxx_oov, tAxxx_ovo, uxIxx_vvo, xAx_o])
    update_code!(func, ein"lmd,lbm,ckd,j->bjck", 1//1, [gxIxx_oov, tAxxx_ovo, uxxxI_vov, xAx_o])
    update_code!(func, ein"lmd,mbl,ckd,j->bjck", 1//1, [gxIxx_oov, tAxxx_ovo, uxxxI_vov, xAx_o])
    update_code!(func, ein"lmd,bcl,jdm,k->bjck", 1//1, [gxIxx_oov, txIxx_vvo, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,cdj,lbm,k->bjck", 1//1, [gxIxx_oov, txIxx_vvo, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,cdl,mbj,k->bjck", 1//1, [gxIxx_oov, txIxx_vvo, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,blc,jdm,k->bjck", 1//1, [gxIxx_oov, txxxI_vov, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,bmc,ldj,k->bjck", 1//1, [gxIxx_oov, txxxI_vov, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,cld,mbj,k->bjck", 1//1, [gxIxx_oov, txxxI_vov, uAxxx_ovo, xAx_o])
    update_code!(func, ein"lmd,lbj,cdm,k->bjck", -1//1, [gxIxx_oov, uAxxx_ovo, uxIxx_vvo, xAx_o])
    finalize_eT_function(func, "omega_mu2_3_1_s", "doublet_ccsd")
end

println(io, s)
end
