include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("omega_μ2_4_ss.F90", "w") do io
s = let
    func = FortranFunction(("omega_bjck", ["o", "v", "o", "v"]))
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    uAIxx_vo = ("uAIxx_vo", true)
    gAxAx_vv = ("gAxAx_vv", true)
    txIxx_vvo = ("txIxx_vvo", true)
    txxxI_vov = ("txxxI_vov", true)
    uxxxI_vov = ("uxxxI_vov", true)
    gxIxI_oo = ("gxIxI_oo", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    tAIAx_o = ("tAIAx_o", true)
    uxIxx_vvo = ("uxIxx_vvo", true)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    tAxAx_oo = ("tAxAx_oo", true)
    txIxI_vv = ("txIxI_vv", true)
    update_code!(func, ein"bdce,dk,je->jbkc", 2//1, [g_vvvv, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ljmk,bm,lc->jbkc", 2//1, [g_oooo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bdce,ej,dk->jbkc", -2//1, [g_vvvv, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmk,cl,bm->jbkc", -2//1, [g_oooo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bdce,je,kd->jbkc", 2//1, [g_vvvv, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ljmk,lc,mb->jbkc", 2//1, [g_oooo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdce,dj,ek->jbkc", 2//1, [g_vvvv, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ljmk,bl,cm->jbkc", 2//1, [g_oooo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"de,bdk,cej->jbkc", 2//1, [gAxAx_vv, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"de,cej,bkd->jbkc", 2//1, [gAxAx_vv, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"de,cjd,bke->jbkc", -2//1, [gAxAx_vv, txxxI_vov, uxxxI_vov])
    update_code!(func, ein"de,bjd,cke->jbkc", 2//1, [gAxAx_vv, uxxxI_vov, uxxxI_vov])
    update_code!(func, ein"lm,jcl,kbm->jbkc", 2//1, [gxIxI_oo, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lm,jcl,mbk->jbkc", 2//1, [gxIxI_oo, tAxxx_ovo, tAxxx_ovo])
    update_code!(func, ein"lm,lcj,mbk->jbkc", -2//1, [gxIxI_oo, tAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"lm,lbj,mck->jbkc", 2//1, [gxIxI_oo, uAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"ldme,cmdj,l,bek->jbkc", -2//1, [g_ovov, t_vovo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ldme,cjdm,l,bke->jbkc", -2//1, [g_ovov, t_vovo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"ldme,bmcl,dj,ke->jbkc", 2//1, [g_ovov, t_vovo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ldme,dkej,bl,mc->jbkc", 2//1, [g_ovov, t_vovo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ldme,blcm,dk,ej->jbkc", -2//1, [g_ovov, t_vovo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,djek,cl,bm->jbkc", -2//1, [g_ovov, t_vovo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,bmcl,jd,ke->jbkc", 2//1, [g_ovov, t_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,dkej,lb,mc->jbkc", 2//1, [g_ovov, t_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,blcm,dj,ek->jbkc", 2//1, [g_ovov, t_vovo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,djek,bl,cm->jbkc", 2//1, [g_ovov, t_vovo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,l,cej,bmdk->jbkc", -2//1, [g_ovov, tAIAx_o, txIxx_vvo, u_vovo])
    update_code!(func, ein"ldme,l,cje,bkdm->jbkc", -2//1, [g_ovov, tAIAx_o, txxxI_vov, u_vovo])
    update_code!(func, ein"ldme,jl,bek,cdm->jbkc", 2//1, [g_ovov, tAxAx_oo, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"ldme,lm,bdk,cej->jbkc", 2//1, [g_ovov, tAxAx_oo, txIxx_vvo, txIxx_vvo])
    update_code!(func, ein"ldme,lm,cej,bkd->jbkc", 2//1, [g_ovov, tAxAx_oo, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"ldme,kl,cej,bmd->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxx_vvo, uxxxI_vov])
    update_code!(func, ein"ldme,kl,bmd,cje->jbkc", 2//1, [g_ovov, tAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,jl,cmd,bek->jbkc", -2//1, [g_ovov, tAxAx_oo, txxxI_vov, uxIxx_vvo])
    update_code!(func, ein"ldme,lm,cjd,bke->jbkc", -2//1, [g_ovov, tAxAx_oo, txxxI_vov, uxxxI_vov])
    update_code!(func, ein"ldme,lm,bjd,cke->jbkc", 2//1, [g_ovov, tAxAx_oo, uxxxI_vov, uxxxI_vov])
    update_code!(func, ein"ldme,jcl,kbm,de->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,jcl,mbk,de->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,lcj,de,mbk->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,de,lbj,mck->jbkc", 2//1, [g_ovov, txIxI_vv, uAxxx_ovo, uAxxx_ovo])
    finalize_eT_function(func, "omega_μ2_4_ss", "ccsd")
end

println(io, s)
end
