include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("omega_μ2_4_s.F90", "w") do io
s = let
    func = FortranFunction(("omega_bjck", ["o", "v", "o", "v"]))
    L_voov = ("L_voov", true)
    tAIAx_o = ("tAIAx_o", true)
    uxxxI_vov = ("uxxxI_vov", true)
    tAIxI_v = ("tAIxI_v", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    uAIxx_vo = ("uAIxx_vo", true)
    tAxAx_oo = ("tAxAx_oo", true)
    txIxI_vv = ("txIxI_vv", true)
    LAxxx_vvv = ("LAxxx_vvv", true)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAxxx_voo = ("LAxxx_voo", true)
    LxIxx_ooo = ("LxIxx_ooo", true)
    LxxxI_vvo = ("LxxxI_vvo", true)
    g_vvoo = ("g_vvoo", true)
    uxIxx_vvo = ("uxIxx_vvo", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_voov = ("g_voov", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    gAIxx_ov = ("gAIxx_ov", true)
    txIxx_vvo = ("txIxx_vvo", true)
    txxxI_vov = ("txxxI_vov", true)
    gAxAx_vv = ("gAxAx_vv", true)
    gAxxI_vo = ("gAxxI_vo", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    gAxxx_vvv = ("gAxxx_vvv", true)
    gAxxx_voo = ("gAxxx_voo", true)
    gAxxx_oov = ("gAxxx_oov", true)
    gxIxI_oo = ("gxIxI_oo", true)
    gxIxx_vov = ("gxIxx_vov", true)
    gxIxx_ooo = ("gxIxx_ooo", true)
    gxxxI_vvo = ("gxxxI_vvo", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"bjld,l,ckd->jbkc", -2//1, [L_voov, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bjld,d,lck->jbkc", -2//1, [L_voov, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bjld,cl,kd->jbkc", 2//1, [L_voov, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bjld,dk,cl->jbkc", -2//1, [L_voov, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bjld,kl,cd->jbkc", 2//1, [L_voov, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bjld,kd,lc->jbkc", 2//1, [L_voov, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"dbe,d,ckej->jbkc", 2//1, [LAxxx_vvv, tAIxI_v, u_vovo])
    update_code!(func, ein"dlj,d,blck->jbkc", -2//1, [LAxxx_voo, tAIxI_v, u_vovo])
    update_code!(func, ein"lmj,l,bmck->jbkc", 2//1, [LxIxx_ooo, tAIAx_o, u_vovo])
    update_code!(func, ein"bdl,l,ckdj->jbkc", -2//1, [LxxxI_vvo, tAIAx_o, u_vovo])
    update_code!(func, ein"bdlk,l,cdj->jbkc", 2//1, [g_vvoo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ljmk,l,bcm->jbkc", -2//1, [g_oooo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"bkld,l,cjd->jbkc", 2//1, [g_voov, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"bkld,d,lcj->jbkc", 2//1, [g_voov, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdce,d,jek->jbkc", -2//1, [g_vvvv, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bdlk,d,jcl->jbkc", 2//1, [g_vvoo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"bkld,cl,jd->jbkc", -2//1, [g_voov, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"bkld,dj,cl->jbkc", 2//1, [g_voov, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"bkld,jl,cd->jbkc", -2//1, [g_voov, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bdlk,jl,cd->jbkc", -2//1, [g_vvoo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"bkld,jd,lc->jbkc", -2//1, [g_voov, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"bdlk,cl,dj->jbkc", -2//1, [g_vvoo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ld,bcl,jdk->jbkc", 2//1, [gAIxx_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bdk,jcl->jbkc", 2//1, [gAIxx_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ld,bkd,lcj->jbkc", 2//1, [gAIxx_ov, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ld,blck,dj->jbkc", -2//1, [gAIxx_ov, u_vovo, uAIxx_vo])
    update_code!(func, ein"ld,ckdj,bl->jbkc", -2//1, [gAIxx_ov, u_vovo, uAIxx_vo])
    update_code!(func, ein"ld,lbj,ckd->jbkc", -2//1, [gAIxx_ov, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"de,bd,ckej->jbkc", -2//1, [gAxAx_vv, txIxI_vv, u_vovo])
    update_code!(func, ein"dl,bl,ckdj->jbkc", 2//1, [gAxxI_vo, tAIxx_vo, u_vovo])
    update_code!(func, ein"dl,dj,blck->jbkc", 2//1, [gAxxI_vo, tAIxx_vo, u_vovo])
    update_code!(func, ein"dl,jd,blck->jbkc", 2//1, [gAxxI_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"dl,lb,ckdj->jbkc", 2//1, [gAxxI_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"dl,jcl,bdk->jbkc", -2//1, [gAxxI_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dl,jdk,bcl->jbkc", -2//1, [gAxxI_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dl,lbk,cdj->jbkc", -2//1, [gAxxI_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"dl,jdk,blc->jbkc", -2//1, [gAxxI_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"dl,bkd,lcj->jbkc", 2//1, [gAxxI_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"dl,lbj,ckd->jbkc", -2//1, [gAxxI_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"dbe,ek,cdj->jbkc", 2//1, [gAxxx_vvv, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"dlj,cl,bdk->jbkc", -2//1, [gAxxx_voo, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"jld,cl,bkd->jbkc", -2//1, [gAxxx_oov, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"jld,dk,blc->jbkc", -2//1, [gAxxx_oov, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"dbe,dk,cej->jbkc", -2//1, [gAxxx_vvv, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"jld,bl,ckd->jbkc", 2//1, [gAxxx_oov, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dbe,dj,cke->jbkc", -2//1, [gAxxx_vvv, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dlj,dk,blc->jbkc", 2//1, [gAxxx_voo, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dbe,ke,cdj->jbkc", 2//1, [gAxxx_vvv, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"dlj,lc,bdk->jbkc", -2//1, [gAxxx_voo, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"jld,kd,blc->jbkc", -2//1, [gAxxx_oov, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"jld,lc,bkd->jbkc", -2//1, [gAxxx_oov, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"dbe,kd,cej->jbkc", -2//1, [gAxxx_vvv, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"jld,lb,ckd->jbkc", 2//1, [gAxxx_oov, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dbe,jd,cke->jbkc", -2//1, [gAxxx_vvv, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"dlj,kd,blc->jbkc", 2//1, [gAxxx_voo, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"jld,kbl,cd->jbkc", -2//1, [gAxxx_oov, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"jld,lbk,cd->jbkc", -2//1, [gAxxx_oov, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dbe,jdk,ce->jbkc", 2//1, [gAxxx_vvv, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"dbe,kdj,ce->jbkc", 2//1, [gAxxx_vvv, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"jld,bd,lck->jbkc", 2//1, [gAxxx_oov, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dbe,cd,kej->jbkc", -2//1, [gAxxx_vvv, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dlj,bd,lck->jbkc", 2//1, [gAxxx_voo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"dlj,cd,kbl->jbkc", 2//1, [gAxxx_voo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"jld,bcl,dk->jbkc", 2//1, [gAxxx_oov, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"jld,bdk,cl->jbkc", 2//1, [gAxxx_oov, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"dbe,cjd,ek->jbkc", -2//1, [gAxxx_vvv, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dlj,bkd,cl->jbkc", 2//1, [gAxxx_voo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"dbe,ej,ckd->jbkc", 2//1, [gAxxx_vvv, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"dlj,bl,ckd->jbkc", -2//1, [gAxxx_voo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"lm,jl,bmck->jbkc", -2//1, [gxIxI_oo, tAxAx_oo, u_vovo])
    update_code!(func, ein"bld,cl,kdj->jbkc", -2//1, [gxIxx_vov, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bld,dk,lcj->jbkc", -2//1, [gxIxx_vov, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"lmj,cm,kbl->jbkc", 2//1, [gxIxx_ooo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bld,dj,lck->jbkc", 2//1, [gxIxx_vov, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,bl,mck->jbkc", -2//1, [gxIxx_ooo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"lmj,cl,kbm->jbkc", -2//1, [gxIxx_ooo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bld,kl,cdj->jbkc", -2//1, [gxIxx_vov, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"lmj,km,bcl->jbkc", 2//1, [gxIxx_ooo, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"bld,kl,cjd->jbkc", -2//1, [gxIxx_vov, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"lmj,km,blc->jbkc", 2//1, [gxIxx_ooo, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"bld,jl,ckd->jbkc", 2//1, [gxIxx_vov, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"lmj,kl,bmc->jbkc", -2//1, [gxIxx_ooo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"bld,kd,lcj->jbkc", -2//1, [gxIxx_vov, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bld,lc,kdj->jbkc", -2//1, [gxIxx_vov, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"lmj,mc,kbl->jbkc", 2//1, [gxIxx_ooo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bld,jd,lck->jbkc", 2//1, [gxIxx_vov, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmj,lb,mck->jbkc", -2//1, [gxIxx_ooo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"lmj,lc,kbm->jbkc", -2//1, [gxIxx_ooo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bld,jcl,dk->jbkc", 2//1, [gxIxx_vov, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bld,jdk,cl->jbkc", 2//1, [gxIxx_vov, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmj,lbk,cm->jbkc", -2//1, [gxIxx_ooo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"lmj,bm,lck->jbkc", 2//1, [gxIxx_ooo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,dk,jcl->jbkc", -2//1, [gxxxI_vvo, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"bdl,cl,kdj->jbkc", 2//1, [gxxxI_vvo, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"bdl,kl,cdj->jbkc", 2//1, [gxxxI_vvo, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"bdl,jl,ckd->jbkc", 2//1, [gxxxI_vvo, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"bdl,kd,jcl->jbkc", -2//1, [gxxxI_vvo, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"bdl,lc,kdj->jbkc", 2//1, [gxxxI_vvo, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"bdl,lcj,dk->jbkc", 2//1, [gxxxI_vvo, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"bdl,dj,lck->jbkc", -2//1, [gxxxI_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,l,ckem,bjd->jbkc", -2//1, [L_ovov, tAIAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,d,ckem,lbj->jbkc", -2//1, [L_ovov, tAIxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,jd,ckem->jbkc", 2//1, [L_ovov, tAIxx_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,dj,ckem,bl->jbkc", -2//1, [L_ovov, tAIxx_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,jl,bd,ckem->jbkc", 2//1, [L_ovov, tAxAx_oo, txIxI_vv, u_vovo])
    update_code!(func, ein"ldme,jd,lb,ckem->jbkc", 2//1, [L_ovov, tAxxI_ov, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,djek,l,bcm->jbkc", -2//1, [g_ovov, t_vovo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"ldme,bkel,d,mcj->jbkc", -2//1, [g_ovov, t_vovo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ldme,blcm,d,jek->jbkc", -2//1, [g_ovov, t_vovo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ldme,blek,d,jcm->jbkc", -2//1, [g_ovov, t_vovo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"ldme,cjdm,bl,ke->jbkc", 2//1, [g_ovov, t_vovo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"ldme,bkel,dj,cm->jbkc", -2//1, [g_ovov, t_vovo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,bkdm,jl,ce->jbkc", 2//1, [g_ovov, t_vovo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ldme,bmdk,jl,ce->jbkc", 2//1, [g_ovov, t_vovo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"ldme,bkel,jd,mc->jbkc", 2//1, [g_ovov, t_vovo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"ldme,blek,cm,dj->jbkc", 2//1, [g_ovov, t_vovo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,l,bjcm,dek->jbkc", 2//1, [g_ovov, tAIAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,l,ckdj,bem->jbkc", 2//1, [g_ovov, tAIAx_o, u_vovo, uxIxx_vvo])
    update_code!(func, ein"ldme,l,bjek,cmd->jbkc", 2//1, [g_ovov, tAIAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,l,cjem,bkd->jbkc", 2//1, [g_ovov, tAIAx_o, u_vovo, uxxxI_vov])
    update_code!(func, ein"ldme,d,blck,jem->jbkc", 2//1, [g_ovov, tAIxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,bmck,lej->jbkc", 2//1, [g_ovov, tAIxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,cjem,lbk->jbkc", 2//1, [g_ovov, tAIxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,d,ckej,lbm->jbkc", 2//1, [g_ovov, tAIxI_v, u_vovo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,kd,cjem->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,bl,md,ckej->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,dj,le,bmck->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,bl,jek,cdm->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,bl,mdk,cej->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,dj,mbk,cel->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,dm,lbk,cej->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,bl,jcm,dke->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,bl,kdm,cje->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,dj,kbm,cle->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,dj,lcm,bke->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,dj,lek,bmc->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,dm,jek,blc->jbkc", 2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,bl,jdk,cem->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,dj,lbk,cem->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bl,jdm,cke->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,dj,lbm,cke->jbkc", -2//1, [g_ovov, tAIxx_vo, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,bl,dej,mck->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,dek,jcm->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bcl,kem->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bcm,lek->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bek,lcm->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bel,mck->jbkc", -2//1, [g_ovov, tAIxx_vo, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cjd,kem->jbkc", -2//1, [g_ovov, tAIxx_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,bl,cmd,jek->jbkc", -2//1, [g_ovov, tAIxx_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,dm,bke,lcj->jbkc", -2//1, [g_ovov, tAIxx_vo, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,dj,bkem,cl->jbkc", 2//1, [g_ovov, tAIxx_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dm,blck,ej->jbkc", 2//1, [g_ovov, tAIxx_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dm,ckej,bl->jbkc", 2//1, [g_ovov, tAIxx_vo, u_vovo, uAIxx_vo])
    update_code!(func, ein"ldme,dj,lck,bem->jbkc", 2//1, [g_ovov, tAIxx_vo, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,bl,jem,ckd->jbkc", 2//1, [g_ovov, tAIxx_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,dm,lbj,cke->jbkc", 2//1, [g_ovov, tAIxx_vo, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,jl,cd,bkem->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxI_vv, u_vovo])
    update_code!(func, ein"ldme,jl,de,bmck->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxI_vv, u_vovo])
    update_code!(func, ein"ldme,lm,bd,ckej->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxI_vv, u_vovo])
    update_code!(func, ein"ldme,jl,bcm,dke->jbkc", 2//1, [g_ovov, tAxAx_oo, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"ldme,jl,cdm,bke->jbkc", 2//1, [g_ovov, tAxAx_oo, txIxx_vvo, txxxI_vov])
    update_code!(func, ein"ldme,jl,bdk,cem->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxx_vvo, uxIxx_vvo])
    update_code!(func, ein"ldme,jl,dek,bcm->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxx_vvo, uxIxx_vvo])
    update_code!(func, ein"ldme,jl,bdm,cke->jbkc", -2//1, [g_ovov, tAxAx_oo, txIxx_vvo, uxxxI_vov])
    update_code!(func, ein"ldme,jl,bmc,dke->jbkc", 2//1, [g_ovov, tAxAx_oo, txxxI_vov, txxxI_vov])
    update_code!(func, ein"ldme,jl,bkd,cem->jbkc", -2//1, [g_ovov, tAxAx_oo, txxxI_vov, uxIxx_vvo])
    update_code!(func, ein"ldme,jl,bmd,cke->jbkc", -2//1, [g_ovov, tAxAx_oo, txxxI_vov, uxxxI_vov])
    update_code!(func, ein"ldme,jl,bem,ckd->jbkc", 2//1, [g_ovov, tAxAx_oo, uxIxx_vvo, uxxxI_vov])
    update_code!(func, ein"ldme,jd,lc,bkem->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,jd,le,bmck->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,lb,md,ckej->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxI_ov, u_vovo])
    update_code!(func, ein"ldme,jd,mbk,cel->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,lb,mdk,cej->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,mb,jcl,dek->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,mb,jdk,cel->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,md,lbk,cej->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txIxx_vvo])
    update_code!(func, ein"ldme,jd,lcm,bke->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,jd,lek,bmc->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,ke,jcl,bmd->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,lc,jdm,bke->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,le,jdk,bmc->jbkc", 2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, txxxI_vov])
    update_code!(func, ein"ldme,jd,lbk,cem->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,lb,jdk,cem->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,jd,lbm,cke->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,lb,jdm,cke->jbkc", -2//1, [g_ovov, tAxxI_ov, tAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,jd,bcl,kem->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,jd,bcm,lek->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,jd,bek,lcm->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,jd,bel,mck->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,lb,dej,mck->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,lb,dek,jcm->jbkc", -2//1, [g_ovov, tAxxI_ov, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"ldme,lb,cjd,kem->jbkc", -2//1, [g_ovov, tAxxI_ov, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,lb,cmd,jek->jbkc", -2//1, [g_ovov, tAxxI_ov, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,le,bkd,mcj->jbkc", -2//1, [g_ovov, tAxxI_ov, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"ldme,jd,lck,bem->jbkc", 2//1, [g_ovov, tAxxI_ov, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"ldme,lb,jem,ckd->jbkc", 2//1, [g_ovov, tAxxI_ov, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,le,mbj,ckd->jbkc", 2//1, [g_ovov, tAxxI_ov, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"ldme,jcl,kdm,be->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,jdk,lbm,ce->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,jdk,lcm,be->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,jdm,lbk,ce->jbkc", 2//1, [g_ovov, tAxxx_ovo, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"ldme,jcl,bd,kem->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,jdm,be,lck->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,lbk,cd,jem->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,lbm,cd,kej->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,lej,bd,mck->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,lej,cd,kbm->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"ldme,jcl,bdm,ek->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,jcl,bek,dm->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,jdk,bcm,el->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,jdk,bel,cm->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,jdm,bcl,ek->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,jdm,bek,cl->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,lbk,dej,cm->jbkc", -2//1, [g_ovov, tAxxx_ovo, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"ldme,lbk,cmd,ej->jbkc", -2//1, [g_ovov, tAxxx_ovo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"ldme,lbm,cjd,ek->jbkc", -2//1, [g_ovov, tAxxx_ovo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"ldme,lej,bkd,cm->jbkc", -2//1, [g_ovov, tAxxx_ovo, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"ldme,jcl,dk,bem->jbkc", 2//1, [g_ovov, tAxxx_ovo, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"ldme,jdk,cl,bem->jbkc", 2//1, [g_ovov, tAxxx_ovo, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"ldme,lbm,ej,ckd->jbkc", 2//1, [g_ovov, tAxxx_ovo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ldme,lej,bm,ckd->jbkc", 2//1, [g_ovov, tAxxx_ovo, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"ldme,bd,jem,lck->jbkc", 2//1, [g_ovov, txIxI_vv, uAxxx_ovo, uAxxx_ovo])
    update_code!(func, ein"ldme,bcl,dk,jem->jbkc", 2//1, [g_ovov, txIxx_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,bcl,em,jdk->jbkc", 2//1, [g_ovov, txIxx_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,bdk,cl,jem->jbkc", 2//1, [g_ovov, txIxx_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,bdk,em,jcl->jbkc", 2//1, [g_ovov, txIxx_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,dej,bm,lck->jbkc", 2//1, [g_ovov, txIxx_vvo, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,bkd,em,lcj->jbkc", 2//1, [g_ovov, txxxI_vov, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,ble,dj,mck->jbkc", 2//1, [g_ovov, txxxI_vov, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"ldme,blck,dj,em->jbkc", -2//1, [g_ovov, u_vovo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,ckdj,bl,em->jbkc", -2//1, [g_ovov, u_vovo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"ldme,dl,mbj,cke->jbkc", -2//1, [g_ovov, uAIxx_vo, uAxxx_ovo, uxxxI_vov])
    finalize_eT_function(func, "omega_μ2_4_s", "ccsd")
end

println(io, s)
end
