include("../TensorOperation-eT-code/src/omeinsum_impl.jl")
open("triples_into_singles_J.F90", "w") do io
s = let
    func = FortranFunction(("rho_ai", ["v", "o"]))
    LAIxx_vo = ("LAIxx_vo", true)
    rAI = ("rAI", true)
    gAIAI = ("gAIAI", true)
    r_vo = ("r_vo", true)
    gAIAx_o = ("gAIAx_o", true)
    rxI_v = ("rxI_v", true)
    gAIxI_v = ("gAIxI_v", true)
    rAx_o = ("rAx_o", true)
    F_vv = ("wf%fock_ab", false)
    uAIxx_vo = ("uAIxx_vo", true)
    F_oo = ("wf%fock_ij", false)
    tAIxI_v = ("tAIxI_v", true)
    tAIAx_o = ("tAIAx_o", true)
    FAx_v = ("FAx_v", true)
    uxxxI_vov = ("uxxxI_vov", true)
    txIxI_vv = ("txIxI_vv", true)
    tAIxx_vo = ("tAIxx_vo", true)
    tAxxI_ov = ("tAxxI_ov", true)
    FxI_o = ("FxI_o", true)
    uAxxx_ovo = ("uAxxx_ovo", true)
    tAxAx_oo = ("tAxAx_oo", true)
    L_voov = ("L_voov", true)
    LAIxx_ov = ("LAIxx_ov", true)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    LAxxx_vvv = ("LAxxx_vvv", true)
    LAxxx_voo = ("LAxxx_voo", true)
    LxIxx_ooo = ("LxIxx_ooo", true)
    LxxxI_vvo = ("LxxxI_vvo", true)
    gAIxx_ov = ("gAIxx_ov", true)
    uxIxx_vvo = ("uxIxx_vvo", true)
    gAxAx_vv = ("gAxAx_vv", true)
    txIxx_vvo = ("txIxx_vvo", true)
    gAxxI_vo = ("gAxxI_vo", true)
    txxxI_vov = ("txxxI_vov", true)
    tAxxx_ovo = ("tAxxx_ovo", true)
    gAxxx_oov = ("gAxxx_oov", true)
    gAxxx_vvv = ("gAxxx_vvv", true)
    gAxxx_voo = ("gAxxx_voo", true)
    gxIxI_oo = ("gxIxI_oo", true)
    gxIxx_vov = ("gxIxx_vov", true)
    gxIxx_ooo = ("gxIxx_ooo", true)
    gxxxI_vvo = ("gxxxI_vvo", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"bj,->bj", 1//1, [LAIxx_vo, rAI])
    update_code!(func, ein",bj->bj", 1//1, [gAIAI, r_vo])
    update_code!(func, ein"j,b->bj", -1//1, [gAIAx_o, rxI_v])
    update_code!(func, ein"b,j->bj", -1//1, [gAIxI_v, rAx_o])
    update_code!(func, ein"bc,,cj->bj", 1//1, [F_vv, rAI, uAIxx_vo])
    update_code!(func, ein"kj,,bk->bj", -1//1, [F_oo, rAI, uAIxx_vo])
    update_code!(func, ein"bc,j,c->bj", -1//1, [F_vv, rAx_o, tAIxI_v])
    update_code!(func, ein"kj,b,k->bj", 1//1, [F_oo, rxI_v, tAIAx_o])
    update_code!(func, ein"c,bj,c->bj", 2//1, [FAx_v, r_vo, tAIxI_v])
    update_code!(func, ein"c,,bjc->bj", 1//1, [FAx_v, rAI, uxxxI_vov])
    update_code!(func, ein"c,j,bc->bj", -1//1, [FAx_v, rAx_o, txIxI_vv])
    update_code!(func, ein"c,b,cj->bj", -1//1, [FAx_v, rxI_v, tAIxx_vo])
    update_code!(func, ein"c,b,jc->bj", -1//1, [FAx_v, rxI_v, tAxxI_ov])
    update_code!(func, ein"k,bj,k->bj", -2//1, [FxI_o, r_vo, tAIAx_o])
    update_code!(func, ein"k,,kbj->bj", -1//1, [FxI_o, rAI, uAxxx_ovo])
    update_code!(func, ein"k,j,bk->bj", 1//1, [FxI_o, rAx_o, tAIxx_vo])
    update_code!(func, ein"k,j,kb->bj", 1//1, [FxI_o, rAx_o, tAxxI_ov])
    update_code!(func, ein"k,b,jk->bj", 1//1, [FxI_o, rxI_v, tAxAx_oo])
    update_code!(func, ein"bjkc,,ck->bj", 1//1, [L_voov, rAI, uAIxx_vo])
    update_code!(func, ein"bjkc,k,c->bj", -1//1, [L_voov, rAx_o, tAIxI_v])
    update_code!(func, ein"bjkc,c,k->bj", -1//1, [L_voov, rxI_v, tAIAx_o])
    update_code!(func, ein"kc,,bjck->bj", 1//1, [LAIxx_ov, rAI, u_vovo])
    update_code!(func, ein"cbd,dj,c->bj", 1//1, [LAxxx_vvv, r_vo, tAIxI_v])
    update_code!(func, ein"ckj,bk,c->bj", -1//1, [LAxxx_voo, r_vo, tAIxI_v])
    update_code!(func, ein"klj,bl,k->bj", 1//1, [LxIxx_ooo, r_vo, tAIAx_o])
    update_code!(func, ein"bck,cj,k->bj", -1//1, [LxxxI_vvo, r_vo, tAIAx_o])
    update_code!(func, ein"kc,bj,ck->bj", 2//1, [gAIxx_ov, r_vo, uAIxx_vo])
    update_code!(func, ein"kc,bk,cj->bj", -1//1, [gAIxx_ov, r_vo, uAIxx_vo])
    update_code!(func, ein"kc,cj,bk->bj", -1//1, [gAIxx_ov, r_vo, uAIxx_vo])
    update_code!(func, ein"kc,j,bck->bj", -1//1, [gAIxx_ov, rAx_o, uxIxx_vvo])
    update_code!(func, ein"kc,k,bjc->bj", -1//1, [gAIxx_ov, rAx_o, uxxxI_vov])
    update_code!(func, ein"kc,b,jck->bj", -1//1, [gAIxx_ov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"kc,c,kbj->bj", -1//1, [gAIxx_ov, rxI_v, uAxxx_ovo])
    update_code!(func, ein"cd,bj,cd->bj", 1//1, [gAxAx_vv, r_vo, txIxI_vv])
    update_code!(func, ein"cd,cj,bd->bj", -1//1, [gAxAx_vv, r_vo, txIxI_vv])
    update_code!(func, ein"cd,b,cdj->bj", -1//1, [gAxAx_vv, rxI_v, txIxx_vvo])
    update_code!(func, ein"cd,c,bjd->bj", 1//1, [gAxAx_vv, rxI_v, uxxxI_vov])
    update_code!(func, ein"ck,bj,ck->bj", -2//1, [gAxxI_vo, r_vo, tAIxx_vo])
    update_code!(func, ein"ck,bk,cj->bj", 1//1, [gAxxI_vo, r_vo, tAIxx_vo])
    update_code!(func, ein"ck,cj,bk->bj", 1//1, [gAxxI_vo, r_vo, tAIxx_vo])
    update_code!(func, ein"ck,bj,kc->bj", -2//1, [gAxxI_vo, r_vo, tAxxI_ov])
    update_code!(func, ein"ck,bk,jc->bj", 1//1, [gAxxI_vo, r_vo, tAxxI_ov])
    update_code!(func, ein"ck,cj,kb->bj", 1//1, [gAxxI_vo, r_vo, tAxxI_ov])
    update_code!(func, ein"ck,j,bck->bj", 1//1, [gAxxI_vo, rAx_o, txIxx_vvo])
    update_code!(func, ein"ck,j,bkc->bj", 1//1, [gAxxI_vo, rAx_o, txxxI_vov])
    update_code!(func, ein"ck,k,bjc->bj", -1//1, [gAxxI_vo, rAx_o, uxxxI_vov])
    update_code!(func, ein"ck,b,jck->bj", 1//1, [gAxxI_vo, rxI_v, tAxxx_ovo])
    update_code!(func, ein"ck,b,kcj->bj", 1//1, [gAxxI_vo, rxI_v, tAxxx_ovo])
    update_code!(func, ein"ck,c,kbj->bj", -1//1, [gAxxI_vo, rxI_v, uAxxx_ovo])
    update_code!(func, ein"jkc,,bck->bj", -1//1, [gAxxx_oov, rAI, uxIxx_vvo])
    update_code!(func, ein"cbd,,cdj->bj", 1//1, [gAxxx_vvv, rAI, uxIxx_vvo])
    update_code!(func, ein"ckj,,bkc->bj", -1//1, [gAxxx_voo, rAI, uxxxI_vov])
    update_code!(func, ein"jkc,k,bc->bj", 1//1, [gAxxx_oov, rAx_o, txIxI_vv])
    update_code!(func, ein"cbd,j,cd->bj", -1//1, [gAxxx_vvv, rAx_o, txIxI_vv])
    update_code!(func, ein"ckj,k,bc->bj", 1//1, [gAxxx_voo, rAx_o, txIxI_vv])
    update_code!(func, ein"jkc,c,bk->bj", 1//1, [gAxxx_oov, rxI_v, tAIxx_vo])
    update_code!(func, ein"cbd,d,cj->bj", -1//1, [gAxxx_vvv, rxI_v, tAIxx_vo])
    update_code!(func, ein"ckj,b,ck->bj", 1//1, [gAxxx_voo, rxI_v, tAIxx_vo])
    update_code!(func, ein"jkc,c,kb->bj", 1//1, [gAxxx_oov, rxI_v, tAxxI_ov])
    update_code!(func, ein"cbd,d,jc->bj", -1//1, [gAxxx_vvv, rxI_v, tAxxI_ov])
    update_code!(func, ein"ckj,b,kc->bj", 1//1, [gAxxx_voo, rxI_v, tAxxI_ov])
    update_code!(func, ein"jkc,b,ck->bj", -1//1, [gAxxx_oov, rxI_v, uAIxx_vo])
    update_code!(func, ein"cbd,c,dj->bj", 1//1, [gAxxx_vvv, rxI_v, uAIxx_vo])
    update_code!(func, ein"ckj,c,bk->bj", -1//1, [gAxxx_voo, rxI_v, uAIxx_vo])
    update_code!(func, ein"kl,bj,kl->bj", 1//1, [gxIxI_oo, r_vo, tAxAx_oo])
    update_code!(func, ein"kl,bk,jl->bj", -1//1, [gxIxI_oo, r_vo, tAxAx_oo])
    update_code!(func, ein"kl,j,kbl->bj", -1//1, [gxIxI_oo, rAx_o, tAxxx_ovo])
    update_code!(func, ein"kl,k,lbj->bj", 1//1, [gxIxI_oo, rAx_o, uAxxx_ovo])
    update_code!(func, ein"bkc,,jck->bj", -1//1, [gxIxx_vov, rAI, uAxxx_ovo])
    update_code!(func, ein"klj,,kbl->bj", 1//1, [gxIxx_ooo, rAI, uAxxx_ovo])
    update_code!(func, ein"bkc,k,cj->bj", 1//1, [gxIxx_vov, rAx_o, tAIxx_vo])
    update_code!(func, ein"klj,l,bk->bj", -1//1, [gxIxx_ooo, rAx_o, tAIxx_vo])
    update_code!(func, ein"bkc,k,jc->bj", 1//1, [gxIxx_vov, rAx_o, tAxxI_ov])
    update_code!(func, ein"klj,l,kb->bj", -1//1, [gxIxx_ooo, rAx_o, tAxxI_ov])
    update_code!(func, ein"bkc,j,ck->bj", -1//1, [gxIxx_vov, rAx_o, uAIxx_vo])
    update_code!(func, ein"klj,k,bl->bj", 1//1, [gxIxx_ooo, rAx_o, uAIxx_vo])
    update_code!(func, ein"bkc,c,jk->bj", 1//1, [gxIxx_vov, rxI_v, tAxAx_oo])
    update_code!(func, ein"klj,b,kl->bj", -1//1, [gxIxx_ooo, rxI_v, tAxAx_oo])
    update_code!(func, ein"bck,,kcj->bj", -1//1, [gxxxI_vvo, rAI, uAxxx_ovo])
    update_code!(func, ein"bck,j,ck->bj", 1//1, [gxxxI_vvo, rAx_o, tAIxx_vo])
    update_code!(func, ein"bck,j,kc->bj", 1//1, [gxxxI_vvo, rAx_o, tAxxI_ov])
    update_code!(func, ein"bck,k,cj->bj", -1//1, [gxxxI_vvo, rAx_o, uAIxx_vo])
    update_code!(func, ein"bck,c,jk->bj", 1//1, [gxxxI_vvo, rxI_v, tAxAx_oo])
    update_code!(func, ein"kcld,ck,l,bjd->bj", -1//1, [L_ovov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"kcld,ck,d,lbj->bj", -1//1, [L_ovov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"kcld,bj,ck,dl->bj", 2//1, [L_ovov, r_vo, tAIxx_vo, tAIxx_vo])
    update_code!(func, ein"kcld,bj,ck,ld->bj", -2//1, [L_ovov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"kcld,ck,bl,jd->bj", 1//1, [L_ovov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"kcld,ck,dj,bl->bj", -1//1, [L_ovov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"kcld,ck,jl,bd->bj", 1//1, [L_ovov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"kcld,ck,jd,lb->bj", 1//1, [L_ovov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"kcld,,bjdl,ck->bj", 1//1, [L_ovov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"kcld,k,c,bjdl->bj", -1//1, [L_ovov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"kcld,c,k,bjdl->bj", -1//1, [L_ovov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"kcld,bj,k,cdl->bj", -2//1, [g_ovov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"kcld,cj,k,bdl->bj", 1//1, [g_ovov, r_vo, tAIAx_o, uxIxx_vvo])
    update_code!(func, ein"kcld,bk,l,cjd->bj", 1//1, [g_ovov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"kcld,cj,l,bkd->bj", 1//1, [g_ovov, r_vo, tAIAx_o, uxxxI_vov])
    update_code!(func, ein"kcld,bj,c,kdl->bj", -2//1, [g_ovov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"kcld,bk,c,jdl->bj", 1//1, [g_ovov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"kcld,bk,d,lcj->bj", 1//1, [g_ovov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"kcld,cj,d,lbk->bj", 1//1, [g_ovov, r_vo, tAIxI_v, uAxxx_ovo])
    update_code!(func, ein"kcld,bk,cl,jd->bj", -1//1, [g_ovov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"kcld,cj,bl,kd->bj", -1//1, [g_ovov, r_vo, tAIxx_vo, tAxxI_ov])
    update_code!(func, ein"kcld,bk,dj,cl->bj", 1//1, [g_ovov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"kcld,cj,dk,bl->bj", 1//1, [g_ovov, r_vo, tAIxx_vo, uAIxx_vo])
    update_code!(func, ein"kcld,bj,kl,cd->bj", 1//1, [g_ovov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"kcld,bk,jl,cd->bj", -1//1, [g_ovov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"kcld,cj,kl,bd->bj", -1//1, [g_ovov, r_vo, tAxAx_oo, txIxI_vv])
    update_code!(func, ein"kcld,bj,kc,ld->bj", 1//1, [g_ovov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"kcld,bj,kd,lc->bj", 1//1, [g_ovov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"kcld,bk,jd,lc->bj", -1//1, [g_ovov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"kcld,cj,kd,lb->bj", -1//1, [g_ovov, r_vo, tAxxI_ov, tAxxI_ov])
    update_code!(func, ein"kcld,bk,cj,dl->bj", -1//1, [g_ovov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"kcld,cj,bk,dl->bj", -1//1, [g_ovov, r_vo, uAIxx_vo, uAIxx_vo])
    update_code!(func, ein"kcld,,bcl,jdk->bj", 1//1, [g_ovov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"kcld,,cdj,kbl->bj", 1//1, [g_ovov, rAI, txIxx_vvo, uAxxx_ovo])
    update_code!(func, ein"kcld,,bkd,lcj->bj", 1//1, [g_ovov, rAI, txxxI_vov, uAxxx_ovo])
    update_code!(func, ein"kcld,,bkdl,cj->bj", -1//1, [g_ovov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"kcld,,cjdl,bk->bj", -1//1, [g_ovov, rAI, u_vovo, uAIxx_vo])
    update_code!(func, ein"kcld,,jck,bdl->bj", -1//1, [g_ovov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"kcld,,kbj,cdl->bj", -1//1, [g_ovov, rAI, uAxxx_ovo, uxIxx_vvo])
    update_code!(func, ein"kcld,,kdl,bjc->bj", -1//1, [g_ovov, rAI, uAxxx_ovo, uxxxI_vov])
    update_code!(func, ein"kcld,j,c,bkdl->bj", 1//1, [g_ovov, rAx_o, tAIxI_v, u_vovo])
    update_code!(func, ein"kcld,k,dj,bcl->bj", -1//1, [g_ovov, rAx_o, tAIxx_vo, txIxx_vvo])
    update_code!(func, ein"kcld,j,cl,bkd->bj", -1//1, [g_ovov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"kcld,k,bl,cjd->bj", -1//1, [g_ovov, rAx_o, tAIxx_vo, txxxI_vov])
    update_code!(func, ein"kcld,j,bk,cdl->bj", 1//1, [g_ovov, rAx_o, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"kcld,k,cj,bdl->bj", 1//1, [g_ovov, rAx_o, tAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"kcld,k,cl,bjd->bj", 1//1, [g_ovov, rAx_o, tAIxx_vo, uxxxI_vov])
    update_code!(func, ein"kcld,k,jd,bcl->bj", -1//1, [g_ovov, rAx_o, tAxxI_ov, txIxx_vvo])
    update_code!(func, ein"kcld,j,kd,blc->bj", -1//1, [g_ovov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"kcld,k,lb,cjd->bj", -1//1, [g_ovov, rAx_o, tAxxI_ov, txxxI_vov])
    update_code!(func, ein"kcld,j,kb,cdl->bj", 1//1, [g_ovov, rAx_o, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"kcld,k,jc,bdl->bj", 1//1, [g_ovov, rAx_o, tAxxI_ov, uxIxx_vvo])
    update_code!(func, ein"kcld,k,lc,bjd->bj", 1//1, [g_ovov, rAx_o, tAxxI_ov, uxxxI_vov])
    update_code!(func, ein"kcld,j,kbl,cd->bj", -1//1, [g_ovov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"kcld,k,jcl,bd->bj", -1//1, [g_ovov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"kcld,k,lcj,bd->bj", -1//1, [g_ovov, rAx_o, tAxxx_ovo, txIxI_vv])
    update_code!(func, ein"kcld,j,bc,kdl->bj", 1//1, [g_ovov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"kcld,k,bc,jdl->bj", 1//1, [g_ovov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"kcld,k,cd,lbj->bj", 1//1, [g_ovov, rAx_o, txIxI_vv, uAxxx_ovo])
    update_code!(func, ein"kcld,j,bcl,dk->bj", 1//1, [g_ovov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"kcld,k,cdj,bl->bj", 1//1, [g_ovov, rAx_o, txIxx_vvo, uAIxx_vo])
    update_code!(func, ein"kcld,k,blc,dj->bj", 1//1, [g_ovov, rAx_o, txxxI_vov, uAIxx_vo])
    update_code!(func, ein"kcld,j,ck,bdl->bj", -1//1, [g_ovov, rAx_o, uAIxx_vo, uxIxx_vvo])
    update_code!(func, ein"kcld,k,dl,bjc->bj", -1//1, [g_ovov, rAx_o, uAIxx_vo, uxxxI_vov])
    update_code!(func, ein"kcld,b,k,cjdl->bj", 1//1, [g_ovov, rxI_v, tAIAx_o, u_vovo])
    update_code!(func, ein"kcld,b,cl,kdj->bj", -1//1, [g_ovov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"kcld,c,bl,jdk->bj", -1//1, [g_ovov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"kcld,c,dj,lbk->bj", -1//1, [g_ovov, rxI_v, tAIxx_vo, tAxxx_ovo])
    update_code!(func, ein"kcld,b,cj,kdl->bj", 1//1, [g_ovov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"kcld,c,bk,jdl->bj", 1//1, [g_ovov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"kcld,c,dk,lbj->bj", 1//1, [g_ovov, rxI_v, tAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"kcld,b,kl,cdj->bj", -1//1, [g_ovov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"kcld,c,jl,bdk->bj", -1//1, [g_ovov, rxI_v, tAxAx_oo, txIxx_vvo])
    update_code!(func, ein"kcld,c,jl,bkd->bj", -1//1, [g_ovov, rxI_v, tAxAx_oo, txxxI_vov])
    update_code!(func, ein"kcld,b,jk,cdl->bj", 1//1, [g_ovov, rxI_v, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"kcld,c,jk,bdl->bj", 1//1, [g_ovov, rxI_v, tAxAx_oo, uxIxx_vvo])
    update_code!(func, ein"kcld,c,kl,bjd->bj", 1//1, [g_ovov, rxI_v, tAxAx_oo, uxxxI_vov])
    update_code!(func, ein"kcld,b,kd,lcj->bj", -1//1, [g_ovov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"kcld,c,jd,lbk->bj", -1//1, [g_ovov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"kcld,c,lb,jdk->bj", -1//1, [g_ovov, rxI_v, tAxxI_ov, tAxxx_ovo])
    update_code!(func, ein"kcld,b,jc,kdl->bj", 1//1, [g_ovov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"kcld,c,kb,jdl->bj", 1//1, [g_ovov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"kcld,c,kd,lbj->bj", 1//1, [g_ovov, rxI_v, tAxxI_ov, uAxxx_ovo])
    update_code!(func, ein"kcld,b,jcl,dk->bj", 1//1, [g_ovov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"kcld,c,kbl,dj->bj", 1//1, [g_ovov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"kcld,c,kdj,bl->bj", 1//1, [g_ovov, rxI_v, tAxxx_ovo, uAIxx_vo])
    update_code!(func, ein"kcld,b,ck,jdl->bj", -1//1, [g_ovov, rxI_v, uAIxx_vo, uAxxx_ovo])
    update_code!(func, ein"kcld,c,dl,kbj->bj", -1//1, [g_ovov, rxI_v, uAIxx_vo, uAxxx_ovo])
    finalize_eT_function(func, "triples_into_singles_J", "doublet_ccsd")
end

println(io, s)
end
